Feature: Syntax checks for RPT - KO 1580

  Background:
    Given systems up
                                                                                                                                                                                                                                                                   

  @ALL @PRIMITIVE @RPTSNTKO @RPTSNTKO_1
  Scenario Outline: Check faultCode PPT_SINTASSI_XSD error on invalid RPT tag
    Given RPT body generation RPT_generation_with_MBD_complete with datatable vertical
      | identificativoDominio             | #creditor_institution_code_old# |
      | identificativoStazioneRichiedente | #id_station#                    |
      | dataOraMessaggioRichiesta         | #timedate#                      |
      | dataEsecuzionePagamento           | #date#                          |
      | importoTotaleDaVersare            | 201                             |
      | codiceIdentificativoUnivoco       | #iuv#                           |
      | identificativoUnivocoVersamento   | #iuv#                           |
      | codiceContestoPagamento           | n/a                             |
      | tipoVersamento                    | BBT                             |
      | importoSingoloVersamento          | 101                             |
      | commissioneCaricoPA               | 125                             |
      | anagraficaPagatore                | Gesualdo;Riccitelli             |
      | indirizzoPagatore                 | via del gesu                    |
      | civicoPagatore                    | 11                              |
    And <elem> with <value> in rptAttachmentBody
    And RPT rptAttachmentBody to base64
    And from body with datatable horizontal pspInviaRPT initial XML pspInviaRPT
      | esitoComplessivoOperazione | identificativoCarrello | parametriPagamentoImmediato |
      | OK                         | $iuv                   | $iuv                        |
    And PSP replies to nodo-dei-pagamenti with the pspInviaRPT
    And from body with datatable vertical nodoInviaRPT initial XML nodoInviaRPT
      | identificativoIntermediarioPA         | #creditor_institution_code#  |
      | identificativoStazioneIntermediarioPA | #id_station#                 |
      | identificativoDominio                 | #creditor_institution_code#  |
      | identificativoUnivocoVersamento       | $iuv                         |
      | codiceContestoPagamento               | CCD01                        |
      | password                              | #password#                   |
      | identificativoPSP                     | #psp#                        |
      | identificativoIntermediarioPSP        | #psp#                        |
      | identificativoCanale                  | #canale_ATTIVATO_PRESSO_PSP# |
      | rpt                                   | $rptAttachment               |
    When EC sends SOAP nodoInviaRPT to nodo-dei-pagamenti
    Then check esito is KO of nodoInviaRPT response
    And check faultCode is PPT_SINTASSI_XSD of nodoInviaRPT response
    Examples:
      | SoapUI      | elem                                    | value                                                                                                                                                                                                                                                                              |
      | RPTSIN1     | pay_i:versioneOggetto                   | None                                                                                                                                                                                                                                                                               |
      | RPTSIN2     | pay_i:versioneOggetto                   | Empty                                                                                                                                                                                                                                                                              |
      | RPTSIN3     | pay_i:versioneOggetto                   | Sono17CaratteAlfa                                                                                                                                                                                                                                                                  |
      | RPTSIN4     | pay_i:dominio                           | None                                                                                                                                                                                                                                                                               |
      | RPTSIN5     | pay_i:identificativoDominio             | None                                                                                                                                                                                                                                                                               |
      | RPTSIN6     | pay_i:identificativoDominio             | Empty                                                                                                                                                                                                                                                                              |
      | RPTSIN7     | pay_i:identificativoDominio             | QuestiSono36CaratteriAlfaNumericiTT1                                                                                                                                                                                                                                               |
      | RPTSIN8     | pay_i:identificativoStazioneRichiedente | Empty                                                                                                                                                                                                                                                                              |
      | RPTSIN8.1   | pay_i:identificativoStazioneRichiedente | None                                                                                                                                                                                                                                                                               |
      | RPTSIN9     | pay_i:identificativoStazioneRichiedente | QuestiSono36CaratteriAlfaNumericiTT1                                                                                                                                                                                                                                               |
      | RPTSIN10    | pay_i:identificativoMessaggioRichiesta  | None                                                                                                                                                                                                                                                                               |
      | RPTSIN11    | pay_i:identificativoMessaggioRichiesta  | Empty                                                                                                                                                                                                                                                                              |
      | RPTSIN12    | pay_i:identificativoMessaggioRichiesta  | QuestiSono36CaratteriAlfaNumericiTT1                                                                                                                                                                                                                                               |
      | RPTSIN13    | pay_i:dataOraMessaggioRichiesta         | None                                                                                                                                                                                                                                                                               |
      | RPTSIN14    | pay_i:dataOraMessaggioRichiesta         | Empty                                                                                                                                                                                                                                                                              |
      | RPTSIN15    | pay_i:dataOraMessaggioRichiesta         | 2001-12-31T12:00:00:0001                                                                                                                                                                                                                                                           |
      | RPTSIN16    | pay_i:dataOraMessaggioRichiesta         | 2001-12-31T12:00                                                                                                                                                                                                                                                                   |
      | RPTSIN17    | pay_i:dataOraMessaggioRichiesta         | 31-12-2001T12:00:00                                                                                                                                                                                                                                                                |
      | RPTSIN18    | pay_i:autenticazioneSoggetto            | None                                                                                                                                                                                                                                                                               |
      | RPTSIN19    | pay_i:autenticazioneSoggetto            | Empty                                                                                                                                                                                                                                                                              |
      | RPTSIN20    | pay_i:autenticazioneSoggetto            | ABS12                                                                                                                                                                                                                                                                              |
      | RPTSIN21    | pay_i:autenticazioneSoggetto            | USP                                                                                                                                                                                                                                                                                |
      | RPTSIN22    | pay_i:soggettoVersante                  | RemoveParent                                                                                                                                                                                                                                                                       |
      | RPTSIN22.1  | pay_i:soggettoVersante                  | None                                                                                                                                                                                                                                                                               |
      | RPTSIN23    | pay_i:identificativoUnivocoVersante     | None                                                                                                                                                                                                                                                                               |
      | RPTSIN24    | pay_i:identificativoUnivocoVersante     | RemoveParent                                                                                                                                                                                                                                                                       |
      | RPTSIN25    | pay_i:tipoIdentificativoUnivoco         | None                                                                                                                                                                                                                                                                               |
      | RPTSIN26    | pay_i:tipoIdentificativoUnivoco         | Empty                                                                                                                                                                                                                                                                              |
      | RPTSIN27    | pay_i:tipoIdentificativoUnivoco         | PP                                                                                                                                                                                                                                                                                 |
      | RPTSIN28    | pay_i:tipoIdentificativoUnivoco         | A                                                                                                                                                                                                                                                                                  |
      | RPTSIN29    | pay_i:codiceIdentificativoUnivoco       | None                                                                                                                                                                                                                                                                               |
      | RPTSIN30    | pay_i:codiceIdentificativoUnivoco       | Empty                                                                                                                                                                                                                                                                              |
      | RPTSIN31    | pay_i:codiceIdentificativoUnivoco       | QuestiSono36CaratteriAlfaNumericiTT1                                                                                                                                                                                                                                               |
      | RPTSIN32    | pay_i:anagraficaVersante                | None                                                                                                                                                                                                                                                                               |
      | RPTSIN33    | pay_i:anagraficaVersante                | Empty                                                                                                                                                                                                                                                                              |
      | RPTSIN34    | pay_i:anagraficaVersante                | QuestiSono71CaratteriAlfaNumericiQuestiSono71CaratteriAlfaNumerici12345                                                                                                                                                                                                            |
      | RPTSIN35    | pay_i:indirizzoVersante                 | Empty                                                                                                                                                                                                                                                                              |
      | RPTSIN35.1  | pay_i:indirizzoVersante                 | None                                                                                                                                                                                                                                                                               |
      | RPTSIN36    | pay_i:indirizzoVersante                 | QuestiSono71CaratteriAlfaNumericiQuestiSono71CaratteriAlfaNumerici12345                                                                                                                                                                                                            |
      | RPTSIN37    | pay_i:civicoVersante                    | Empty                                                                                                                                                                                                                                                                              |
      | RPTSIN37.1  | pay_i:civicoVersante                    | None                                                                                                                                                                                                                                                                               |
      | RPTSIN38    | pay_i:civicoVersante                    | Sono17CaratteAlfa                                                                                                                                                                                                                                                                  |
      | RPTSIN39    | pay_i:capVersante                       | Empty                                                                                                                                                                                                                                                                              |
      | RPTSIN39.1  | pay_i:capVersante                       | None                                                                                                                                                                                                                                                                               |
      | RPTSIN40    | pay_i:capVersante                       | Sono17CaratteAlfa                                                                                                                                                                                                                                                                  |
      | RPTSIN41    | pay_i:localitaVersante                  | Empty                                                                                                                                                                                                                                                                              |
      | RPTSIN41.1  | pay_i:localitaVersante                  | None                                                                                                                                                                                                                                                                               |
      | RPTSIN42    | pay_i:localitaVersante                  | QuestiSono36CaratteriAlfaNumericiTT1                                                                                                                                                                                                                                               |
      | RPTSIN43    | pay_i:provinciaVersante                 | Empty                                                                                                                                                                                                                                                                              |
      | RPTSIN43.1  | pay_i:provinciaVersante                 | None                                                                                                                                                                                                                                                                               |
      | RPTSIN44    | pay_i:provinciaVersante                 | MIprovinciaVersanteprovinciaVersanteprovinciaVersanteprovinciaVersanteprovinciaVersanteprovinciaVersanteprovinciaVersanteprovinciaVersanteprovinciaVersanteprovinciaVersanteprovinciaVersanteprovinciaVersanteprovinciaVersanteprovinciaVersanteprovinciaVersanteprovinciaVersante |
      | RPTSIN45    | pay_i:nazioneVersante                   | Empty                                                                                                                                                                                                                                                                              |
      | RPTSIN45.1  | pay_i:nazioneVersante                   | None                                                                                                                                                                                                                                                                               |
      | RPTSIN46    | pay_i:nazioneVersante                   | AB1                                                                                                                                                                                                                                                                                |
      | RPTSIN47    | pay_i:e-mailVersante                    | Empty                                                                                                                                                                                                                                                                              |
      | RPTSIN47.1  | pay_i:e-mailVersante                    | None                                                                                                                                                                                                                                                                               |
      | RPTSIN47.2  | pay_i:e-mailVersante                    | aaaa.bbbit                                                                                                                                                                                                                                                                         |
      | RPTSIN48    | pay_i:e-mailVersante                    | 257DDDDDDDDDDDDDDDDDDDDDDDDDFFFFFFFFFFFFFFDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDFDDDmail                          |
      | RPTSIN49    | pay_i:soggettoPagatore                  | None                                                                                                                                                                                                                                                                               |
      | RPTSIN50    | pay_i:soggettoPagatore                  | RemoveParent                                                                                                                                                                                                                                                                       |
      | RPTSIN51    | pay_i:identificativoUnivocoPagatore     | None                                                                                                                                                                                                                                                                               |
      | RPTSIN52    | pay_i:identificativoUnivocoPagatore     | RemoveParent                                                                                                                                                                                                                                                                       |
      | RPTSIN53    | pay_i:tipoIdentificativoUnivoco         | None                                                                                                                                                                                                                                                                               |
      | RPTSIN54    | pay_i:tipoIdentificativoUnivoco         | Empty                                                                                                                                                                                                                                                                              |
      | RPTSIN55    | pay_i:tipoIdentificativoUnivoco         | FF                                                                                                                                                                                                                                                                                 |
      | RPTSIN56    | pay_i:tipoIdentificativoUnivoco         | H                                                                                                                                                                                                                                                                                  |
      | RPTSIN57    | pay_i:codiceIdentificativoUnivoco       | None                                                                                                                                                                                                                                                                               |
      | RPTSIN58    | pay_i:codiceIdentificativoUnivoco       | Empty                                                                                                                                                                                                                                                                              |
      | RPTSIN59    | pay_i:codiceIdentificativoUnivoco       | QuestiSono36CaratteriAlfaNumericiTT1                                                                                                                                                                                                                                               |
      | RPTSIN60    | pay_i:anagraficaPagatore                | None                                                                                                                                                                                                                                                                               |
      | RPTSIN61    | pay_i:anagraficaPagatore                | Empty                                                                                                                                                                                                                                                                              |
      | RPTSIN62    | pay_i:anagraficaPagatore                | QuestiSono71CaratteriAlfaNumericiQuestiSono71CaratteriAlfaNumerici12345                                                                                                                                                                                                            |
      | RPTSIN63    | pay_i:indirizzoPagatore                 | Empty                                                                                                                                                                                                                                                                              |
      | RPTSIN63.1  | pay_i:indirizzoPagatore                 | None                                                                                                                                                                                                                                                                               |
      | RPTSIN64    | pay_i:indirizzoPagatore                 | QuestiSono71CaratteriAlfaNumericiQuestiSono71CaratteriAlfaNumerici12345                                                                                                                                                                                                            |
      | RPTSIN65    | pay_i:civicoPagatore                    | Empty                                                                                                                                                                                                                                                                              |
      | RPTSIN65.1  | pay_i:civicoPagatore                    | None                                                                                                                                                                                                                                                                               |
      | RPTSIN66    | pay_i:civicoPagatore                    | Sono17CaratteAlfa                                                                                                                                                                                                                                                                  |
      | RPTSIN67    | pay_i:capPagatore                       | Empty                                                                                                                                                                                                                                                                              |
      | RPTSIN67.1  | pay_i:capPagatore                       | None                                                                                                                                                                                                                                                                               |
      | RPTSIN68    | pay_i:capPagatore                       | Sono17CaratteAlfa                                                                                                                                                                                                                                                                  |
      | RPTSIN69    | pay_i:localitaPagatore                  | Empty                                                                                                                                                                                                                                                                              |
      | RPTSIN69.1  | pay_i:localitaPagatore                  | None                                                                                                                                                                                                                                                                               |
      | RPTSIN70    | pay_i:localitaPagatore                  | QuestiSono36CaratteriAlfaNumericiTT1                                                                                                                                                                                                                                               |
      | RPTSIN71    | pay_i:provinciaPagatore                 | Empty                                                                                                                                                                                                                                                                              |
      | RPTSIN71.1  | pay_i:provinciaPagatore                 | None                                                                                                                                                                                                                                                                               |
      | RPTSIN72    | pay_i:provinciaPagatore                 | QuestiSono36CaratteriAlfaNumericiTT1                                                                                                                                                                                                                                               |
      | RPTSIN73    | pay_i:nazionePagatore                   | Empty                                                                                                                                                                                                                                                                              |
      | RPTSIN73.1  | pay_i:nazionePagatore                   | None                                                                                                                                                                                                                                                                               |
      | RPTSIN74    | pay_i:nazionePagatore                   | AB1                                                                                                                                                                                                                                                                                |
      | RPTSIN75    | pay_i:e-mailPagatore                    | Empty                                                                                                                                                                                                                                                                              |
      | RPTSIN75.1  | pay_i:e-mailPagatore                    | None                                                                                                                                                                                                                                                                               |
      | RPTSIN76    | pay_i:e-mailPagatore                    | 257DDDDDDDDDDDDDDDDDDDDDDDDDFFFFFFFFFFFFFFDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDFDDDmail                          |
      | RPTSIN77    | pay_i:enteBeneficiario                  | None                                                                                                                                                                                                                                                                               |
      | RPTSIN78    | pay_i:enteBeneficiario                  | RemoveParent                                                                                                                                                                                                                                                                       |
      | RPTSIN79    | pay_i:identificativoUnivocoBeneficiario | None                                                                                                                                                                                                                                                                               |
      | RPTSIN80    | pay_i:identificativoUnivocoBeneficiario | RemoveParent                                                                                                                                                                                                                                                                       |
      | RPTSIN81    | pay_i:tipoIdentificativoUnivoco         | None                                                                                                                                                                                                                                                                               |
      | RPTSIN82    | pay_i:tipoIdentificativoUnivoco         | Empty                                                                                                                                                                                                                                                                              |
      | RPTSIN83    | pay_i:tipoIdentificativoUnivoco         | GG                                                                                                                                                                                                                                                                                 |
      | RPTSIN84    | pay_i:tipoIdentificativoUnivoco         | C                                                                                                                                                                                                                                                                                  |
      | RPTSIN85    | pay_i:codiceIdentificativoUnivoco       | None                                                                                                                                                                                                                                                                               |
      | RPTSIN86    | pay_i:codiceIdentificativoUnivoco       | Empty                                                                                                                                                                                                                                                                              |
      | RPTSIN87    | pay_i:codiceIdentificativoUnivoco       | QuestiSono36CaratteriAlfaNumericiTT1                                                                                                                                                                                                                                               |
      | RPTSIN88    | pay_i:denominazioneBeneficiario         | None                                                                                                                                                                                                                                                                               |
      | RPTSIN89    | pay_i:denominazioneBeneficiario         | Empty                                                                                                                                                                                                                                                                              |
      | RPTSIN90    | pay_i:denominazioneBeneficiario         | QuestiSono71CaratteriAlfaNumericiQuestiSono71CaratteriAlfaNumerici12345                                                                                                                                                                                                            |
      | RPTSIN91    | pay_i:codiceUnitOperBeneficiario        | Empty                                                                                                                                                                                                                                                                              |
      | RPTSIN91.1  | pay_i:codiceUnitOperBeneficiario        | None                                                                                                                                                                                                                                                                               |
      | RPTSIN92    | pay_i:codiceUnitOperBeneficiario        | QuestiSono36CaratteriAlfaNumericiTT1                                                                                                                                                                                                                                               |
      | RPTSIN93    | pay_i:denomUnitOperBeneficiario         | Empty                                                                                                                                                                                                                                                                              |
      | RPTSIN93.1  | pay_i:denomUnitOperBeneficiario         | None                                                                                                                                                                                                                                                                               |
      | RPTSIN94    | pay_i:denomUnitOperBeneficiario         | QuestiSono71CaratteriAlfaNumericiQuestiSono71CaratteriAlfaNumerici12345                                                                                                                                                                                                            |
      | RPTSIN95    | pay_i:indirizzoBeneficiario             | Empty                                                                                                                                                                                                                                                                              |
      | RPTSIN95.1  | pay_i:indirizzoBeneficiario             | None                                                                                                                                                                                                                                                                               |
      | RPTSIN96    | pay_i:indirizzoBeneficiario             | QuestiSono71CaratteriAlfaNumericiQuestiSono71CaratteriAlfaNumerici12345                                                                                                                                                                                                            |
      | RPTSIN97    | pay_i:civicoBeneficiario                | Empty                                                                                                                                                                                                                                                                              |
      | RPTSIN97.1  | pay_i:civicoBeneficiario                | None                                                                                                                                                                                                                                                                               |
      | RPTSIN98    | pay_i:civicoBeneficiario                | Sono17CaratteAlfa                                                                                                                                                                                                                                                                  |
      | RPTSIN99    | pay_i:capBeneficiario                   | Empty                                                                                                                                                                                                                                                                              |
      | RPTSIN99.1  | pay_i:capBeneficiario                   | None                                                                                                                                                                                                                                                                               |
      | RPTSIN100   | pay_i:capBeneficiario                   | Sono17CaratteAlfa                                                                                                                                                                                                                                                                  |
      | RPTSIN101   | pay_i:capBeneficiario                   | Empty                                                                                                                                                                                                                                                                              |
      | RPTSIN101.1 | pay_i:capBeneficiario                   | None                                                                                                                                                                                                                                                                               |
      | RPTSIN102   | pay_i:capBeneficiario                   | Sono17CaratteAlfa                                                                                                                                                                                                                                                                  |
      | RPTSIN103   | pay_i:provinciaBeneficiario             | Empty                                                                                                                                                                                                                                                                              |
      | RPTSIN103.1 | pay_i:provinciaBeneficiario             | None                                                                                                                                                                                                                                                                               |
      | RPTSIN104   | pay_i:provinciaBeneficiario             | QuestiSono36CaratteriAlfaNumericiTT1                                                                                                                                                                                                                                               |
      | RPTSIN105   | pay_i:nazioneBeneficiario               | Empty                                                                                                                                                                                                                                                                              |
      | RPTSIN105.1 | pay_i:nazioneBeneficiario               | None                                                                                                                                                                                                                                                                               |
      | RPTSIN106   | pay_i:nazioneBeneficiario               | AB1                                                                                                                                                                                                                                                                                |
      | RPTSIN107   | pay_i:datiVersamento                    | None                                                                                                                                                                                                                                                                               |
      | RPTSIN108   | pay_i:datiVersamento                    | RemoveParent                                                                                                                                                                                                                                                                       |
      | RPTSIN109   | pay_i:dataEsecuzionePagamento           | None                                                                                                                                                                                                                                                                               |
      | RPTSIN110   | pay_i:dataEsecuzionePagamento           | Empty                                                                                                                                                                                                                                                                              |
      | RPTSIN111   | pay_i:dataEsecuzionePagamento           | 2001-12-31T12:00                                                                                                                                                                                                                                                                   |
      | RPTSIN112   | pay_i:dataEsecuzionePagamento           | 2001-12-                                                                                                                                                                                                                                                                           |
      | RPTSIN113   | pay_i:importoTotaleDaVersare            | None                                                                                                                                                                                                                                                                               |
      | RPTSIN114   | pay_i:importoTotaleDaVersare            | Empty                                                                                                                                                                                                                                                                              |
      | RPTSIN115   | pay_i:importoTotaleDaVersare            | 22                                                                                                                                                                                                                                                                                 |
      | RPTSIN116   | pay_i:importoTotaleDaVersare            | 0.00                                                                                                                                                                                                                                                                               |
      | RPTSIN117   | pay_i:importoTotaleDaVersare            | 199999999.99                                                                                                                                                                                                                                                                       |
      | RPTSIN117.1 | pay_i:importoTotaleDaVersare            | 1000000000.00                                                                                                                                                                                                                                                                      |
      | RPTSIN117.2 | pay_i:importoTotaleDaVersare            | 99999999999.00                                                                                                                                                                                                                                                                     |
      | RPTSIN118   | pay_i:importoTotaleDaVersare            | 10.251                                                                                                                                                                                                                                                                             |
      | RPTSIN118.1 | pay_i:importoTotaleDaVersare            | 10.2                                                                                                                                                                                                                                                                               |
      | RPTSIN119   | pay_i:importoTotaleDaVersare            | 10,25                                                                                                                                                                                                                                                                              |
      | RPTSIN120   | pay_i:tipoVersamento                    | None                                                                                                                                                                                                                                                                               |
      | RPTSIN121   | pay_i:tipoVersamento                    | Empty                                                                                                                                                                                                                                                                              |
      | RPTSIN122   | pay_i:tipoVersamento                    | OBEPT                                                                                                                                                                                                                                                                              |
      | RPTSIN123   | pay_i:tipoVersamento                    | BD                                                                                                                                                                                                                                                                                 |
      | RPTSIN124   | pay_i:identificativoUnivocoVersamento   | None                                                                                                                                                                                                                                                                               |
      | RPTSIN125   | pay_i:identificativoUnivocoVersamento   | Empty                                                                                                                                                                                                                                                                              |
      | RPTSIN126   | pay_i:identificativoUnivocoVersamento   | QuestiSono36CaratteriAlfaNumericiTT1                                                                                                                                                                                                                                               |
      | RPTSIN127   | pay_i:codiceContestoPagamento           | None                                                                                                                                                                                                                                                                               |
      | RPTSIN128   | pay_i:codiceContestoPagamento           | Empty                                                                                                                                                                                                                                                                              |
      | RPTSIN129   | pay_i:codiceContestoPagamento           | QuestiSono36CaratteriAlfaNumericiTT1                                                                                                                                                                                                                                               |
      | RPTSIN134   | pay_i:bicAddebito                       | Empty                                                                                                                                                                                                                                                                              |
      | RPTSIN134.1 | pay_i:bicAddebito                       | None                                                                                                                                                                                                                                                                               |
      | RPTSIN135   | pay_i:bicAddebito                       | ABCDEF                                                                                                                                                                                                                                                                             |
      | RPTSIN136   | pay_i:bicAddebito                       | ABCDEFABCDEF                                                                                                                                                                                                                                                                       |
      | RPTSIN137   | pay_i:bicAddebito                       | U2CRITMM                                                                                                                                                                                                                                                                           |
      | RPTSIN138   | pay_i:firmaRicevuta                     | None                                                                                                                                                                                                                                                                               |
      | RPTSIN139   | pay_i:firmaRicevuta                     | Empty                                                                                                                                                                                                                                                                              |
      | RPTSIN139.1 | pay_i:firmaRicevuta                     | 1                                                                                                                                                                                                                                                                                  |
      | RPTSIN139.2 | pay_i:firmaRicevuta                     | 3                                                                                                                                                                                                                                                                                  |
      | RPTSIN140   | pay_i:firmaRicevuta                     | 33                                                                                                                                                                                                                                                                                 |
      | RPTSIN141   | pay_i:firmaRicevuta                     | 4                                                                                                                                                                                                                                                                                  |
      | RPTSIN142   | pay_i:datiSingoloVersamento             | None                                                                                                                                                                                                                                                                               |
      | RPTSIN145   | pay_i:importoSingoloVersamento          | None                                                                                                                                                                                                                                                                               |
      | RPTSIN146   | pay_i:importoSingoloVersamento          | Empty                                                                                                                                                                                                                                                                              |
      | RPTSIN147   | pay_i:importoSingoloVersamento          | 22                                                                                                                                                                                                                                                                                 |
      | RPTSIN148   | pay_i:importoSingoloVersamento          | 0.00                                                                                                                                                                                                                                                                               |
      | RPTSIN149   | pay_i:importoSingoloVersamento          | 19999999.99                                                                                                                                                                                                                                                                        |
      | RPTSIN149.1 | pay_i:importoSingoloVersamento          | 199999999.90                                                                                                                                                                                                                                                                       |
      | RPTSIN149.2 | pay_i:importoSingoloVersamento          | 1999999999.90                                                                                                                                                                                                                                                                      |
      | RPTSIN150   | pay_i:importoSingoloVersamento          | 10.251                                                                                                                                                                                                                                                                             |
      | RPTSIN150.1 | pay_i:importoSingoloVersamento          | 10.1                                                                                                                                                                                                                                                                               |
      | RPTSIN151   | pay_i:importoSingoloVersamento          | 10,25                                                                                                                                                                                                                                                                              |
      | RPTSIN152   | pay_i:commissioneCaricoPA               | Empty                                                                                                                                                                                                                                                                              |
      | RPTSIN152.1 | pay_i:commissioneCaricoPA               | None                                                                                                                                                                                                                                                                               |
      | RPTSIN153   | pay_i:commissioneCaricoPA               | 22                                                                                                                                                                                                                                                                                 |
      | RPTSIN154   | pay_i:commissioneCaricoPA               | a.00                                                                                                                                                                                                                                                                               |
      | RPTSIN155   | pay_i:commissioneCaricoPA               | 1999999999.99                                                                                                                                                                                                                                                                      |
      | RPTSIN155.1 | pay_i:commissioneCaricoPA               | 1999999.90                                                                                                                                                                                                                                                                         |
      | RPTSIN155.1 | pay_i:commissioneCaricoPA               | 199999999999999999.00                                                                                                                                                                                                                                                              |
      | RPTSIN155.2 | pay_i:commissioneCaricoPA               | 19999999999999999.90                                                                                                                                                                                                                                                               |
      | RPTSIN156   | pay_i:commissioneCaricoPA               | 10.251                                                                                                                                                                                                                                                                             |
      | RPTSIN157   | pay_i:commissioneCaricoPA               | 10,25                                                                                                                                                                                                                                                                              |
      | RPTSIN162   | pay_i:bicAccredito                      | Empty                                                                                                                                                                                                                                                                              |
      | RPTSIN162.1 | pay_i:bicAccredito                      | None                                                                                                                                                                                                                                                                               |
      | RPTSIN163   | pay_i:bicAccredito                      | ABCDEF                                                                                                                                                                                                                                                                             |
      | RPTSIN164   | pay_i:bicAccredito                      | ABCDEFABCDEF                                                                                                                                                                                                                                                                       |
      | RPTSIN165   | pay_i:bicAccredito                      | U2CRITMM                                                                                                                                                                                                                                                                           |
      | RPTSIN166   | pay_i:ibanAppoggio                      | Empty                                                                                                                                                                                                                                                                              |
      | RPTSIN166.1 | pay_i:ibanAppoggio                      | None                                                                                                                                                                                                                                                                               |
      | RPTSIN167   | pay_i:ibanAppoggio                      | QuestiSono36CaratteriAlfaNumericiTT1                                                                                                                                                                                                                                               |
      | RPTSIN168   | pay_i:ibanAppoggio                      | XX96R0123454321000000012345                                                                                                                                                                                                                                                        |
      | RPTSIN169   | pay_i:bicAppoggio                       | Empty                                                                                                                                                                                                                                                                              |
      | RPTSIN169.1 | pay_i:bicAppoggio                       | None                                                                                                                                                                                                                                                                               |
      | RPTSIN170   | pay_i:bicAppoggio                       | ABCDEF                                                                                                                                                                                                                                                                             |
      | RPTSIN171   | pay_i:bicAppoggio                       | ABCDEFABCDEF                                                                                                                                                                                                                                                                       |
      | RPTSIN172   | pay_i:bicAppoggio                       | U2CRITMM                                                                                                                                                                                                                                                                           |
      | RPTSIN173   | pay_i:credenzialiPagatore               | Empty                                                                                                                                                                                                                                                                              |
      | RPTSIN173.1 | pay_i:credenzialiPagatore               | None                                                                                                                                                                                                                                                                               |
      | RPTSIN174   | pay_i:credenzialiPagatore               | QuestiSono36CaratteriAlfaNumericiTT1                                                                                                                                                                                                                                               |
      | RPTSIN175   | pay_i:causaleVersamento                 | None                                                                                                                                                                                                                                                                               |
      | RPTSIN176   | pay_i:causaleVersamento                 | Empty                                                                                                                                                                                                                                                                              |
      | RPTSIN177   | pay_i:causaleVersamento                 | QuestiSono141CaratteriAlfaNumericiTT1QuestiSono141CaratteriAlfaNumericiTT1QuestiSono141CaratteriAlfaNumericiTT1QuestiSono141CaratteriAlfaNume                                                                                                                                      |
      | RPTSIN178   | pay_i:datiSpecificiRiscossione          | None                                                                                                                                                                                                                                                                               |
      | RPTSIN179   | pay_i:datiSpecificiRiscossione          | Empty                                                                                                                                                                                                                                                                              |
      | RPTSIN180   | pay_i:datiSpecificiRiscossione          | QuestiSono141CaratteriAlfaNumericiTT1QuestiSono141CaratteriAlfaNumericiTT1QuestiSono141CaratteriAlfaNumericiTT1QuestiSono141CaratteriAlfaNume                                                                                                                                      |
      | RPTSIN181   | pay_i:datiSpecificiRiscossione          | 3/abc                                                                                                                                                                                                                                                                              |
      | RPTSIN182   | pay_i:datiSpecificiRiscossione          | 1.abc                                                                                                                                                                                                                                                                              |
      | RPTSIN185   | pay_i:tipoBollo                         | None                                                                                                                                                                                                                                                                               |
      | RPTSIN186   | pay_i:tipoBollo                         | Empty                                                                                                                                                                                                                                                                              |
      | RPTSIN187   | pay_i:tipoBollo                         | 011                                                                                                                                                                                                                                                                                |
      | RPTSIN188   | pay_i:tipoBollo                         | 02                                                                                                                                                                                                                                                                                 |
      | RPTSIN189   | pay_i:hashDocumento                     | None                                                                                                                                                                                                                                                                               |
      | RPTSIN190   | pay_i:hashDocumento                     | Empty                                                                                                                                                                                                                                                                              |
      | RPTSIN191   | pay_i:hashDocumento                     | QFPAeGzvbUyv9MTOgYIugs7qvGATXgt3VN5jZVFI[yg=                                                                                                                                                                                                                                       |
      | RPTSIN191.1 | pay_i:hashDocumento                     | dGVzdCBkaSBwcm92YSBwZXIgdmVyaWZpY2FyZSBjaGUgbGEgbHVuZ2hlenphIGRlbCBwYXJhbWV0cm8gaGFzaERvY3VtZW50byBub24gc2lhIHBpw7kgbHVuZ2EgZGkgNzAgY2FyYXR0ZXJp                                                                                                                                   |
      | RPTSIN192   | pay_i:provinciaResidenza                | None                                                                                                                                                                                                                                                                               |
      | RPTSIN193   | pay_i:provinciaResidenza                | Empty                                                                                                                                                                                                                                                                              |
      | RPTSIN194   | pay_i:provinciaResidenza                | MIT                                                                                                                                                                                                                                                                                |
      | RPTSIN195   | pay_i:importoSingoloVersamento          | 999999999.99                                                                                                                                                                                                                                                                       |



  @ALL @PRIMITIVE @RPTSNTKO @RPTSNTKO_2
  Scenario Outline: Check faultCode PPT_SINTASSI_XSD error on invalid RPT tag combination
    Given RPT body generation RPT_generation_with_MBD_complete with datatable vertical
      | identificativoDominio             | #creditor_institution_code_old# |
      | identificativoStazioneRichiedente | #id_station#                    |
      | dataOraMessaggioRichiesta         | #timedate#                      |
      | dataEsecuzionePagamento           | #date#                          |
      | importoTotaleDaVersare            | 201                             |
      | codiceIdentificativoUnivoco       | #iuv#                           |
      | identificativoUnivocoVersamento   | #iuv#                           |
      | codiceContestoPagamento           | n/a                             |
      | tipoVersamento                    | BBT                             |
      | importoSingoloVersamento          | 101                             |
      | commissioneCaricoPA               | 125                             |
      | anagraficaPagatore                | Gesualdo;Riccitelli             |
      | indirizzoPagatore                 | via del gesu                    |
      | civicoPagatore                    | 11                              |
    And <elem1> with <value1> in rptAttachmentBody
    And <elem2> with <value2> in rptAttachmentBody
    And RPT rptAttachmentBody to base64
    And from body with datatable horizontal pspInviaRPT initial XML pspInviaRPT
      | esitoComplessivoOperazione | identificativoCarrello | parametriPagamentoImmediato |
      | OK                         | $iuv                   | $iuv                        |
    And PSP replies to nodo-dei-pagamenti with the pspInviaRPT
    And from body with datatable vertical nodoInviaRPT initial XML nodoInviaRPT
      | identificativoIntermediarioPA         | #creditor_institution_code#  |
      | identificativoStazioneIntermediarioPA | #id_station#                 |
      | identificativoDominio                 | #creditor_institution_code#  |
      | identificativoUnivocoVersamento       | $iuv                         |
      | codiceContestoPagamento               | CCD01                        |
      | password                              | #password#                   |
      | identificativoPSP                     | #psp#                        |
      | identificativoIntermediarioPSP        | #psp#                        |
      | identificativoCanale                  | #canale_ATTIVATO_PRESSO_PSP# |
      | rpt                                   | $rptAttachment               |
    When EC sends SOAP nodoInviaRPT to nodo-dei-pagamenti
    Then check esito is KO of nodoInviaRPT response
    And check faultCode is PPT_SINTASSI_XSD of nodoInviaRPT response
    Examples:
      | SoapUI      | elem1                        | value1 | elem2                       | value2                               |
      | RPTSIN130   | pay_i:tipoVersamento         | AD     | pay_i:ibanAddebito          | None                                 |
      | RPTSIN130.1 | pay_i:tipoVersamento         | BBT    | pay_i:ibanAddebito          | None                                 |
      | RPTSIN131   | pay_i:tipoVersamento         | AD     | pay_i:ibanAddebito          | Empty                                |
      | RPTSIN132   | pay_i:tipoVersamento         | AD     | pay_i:ibanAddebito          | QuestiSono36CaratteriAlfaNumericiTT1 |
      | RPTSIN133   | pay_i:tipoVersamento         | AD     | pay_i:ibanAddebito          | X596R0123454321000000012345          |
      | RPTSIN143   | pay_i:tipoVersamento         | PO     | pay_i:datiSingoloVersamento | Occurrences,2                        |
      | RPTSIN144   | pay_i:tipoVersamento         | AD     | pay_i:datiSingoloVersamento | Occurrences,6                        |
      | RPTSIN158   | pay_i:datiMarcaBolloDigitale | None   | pay_i:ibanAccredito         | None                                 |
      | RPTSIN159   | pay_i:datiMarcaBolloDigitale | None   | pay_i:ibanAccredito         | Empty                                |
      | RPTSIN160   | pay_i:datiMarcaBolloDigitale | None   | pay_i:ibanAccredito         | QuestiSono36CaratteriAlfaNumericiTT1 |
      | RPTSIN161   | pay_i:datiMarcaBolloDigitale | None   | pay_i:ibanAccredito         | 1196R0123454321000000012345          |
      | RPTSIN183   | pay_i:datiMarcaBolloDigitale | None   | pay_i:ibanAccredito         | 1196R0123454321000000012345          |
      | RPTSEM10    | pay_i:tipoVersamento         | AD     | pay_i:firmaRicevuta         | 3                                    |
      | RPTSEM11    | pay_i:tipoVersamento         | PO     | pay_i:firmaRicevuta         | 1                                    |



  @ALL @PRIMITIVE @RPTSNTKO @RPTSNTKO_3
  Scenario: Syntax check 2 datiMarcaBolloDigitale and ibanAccredito None [RPTSIN184]
    Given RPT generation RPT_generation_with_2MBD_complete with datatable vertical
      | identificativoDominio             | #creditor_institution_code_old# |
      | identificativoStazioneRichiedente | #id_station#                    |
      | dataOraMessaggioRichiesta         | #timedate#                      |
      | dataEsecuzionePagamento           | #date#                          |
      | importoTotaleDaVersare            | 201                             |
      | codiceIdentificativoUnivoco       | #iuv#                           |
      | identificativoUnivocoVersamento   | #iuv#                           |
      | codiceContestoPagamento           | n/a                             |
      | tipoVersamento                    | BBT                             |
      | importoSingoloVersamento          | 101                             |
      | commissioneCaricoPA               | 125                             |
      | anagraficaPagatore                | Gesualdo;Riccitelli             |
      | indirizzoPagatore                 | via del gesu                    |
      | civicoPagatore                    | 11                              |
    And from body with datatable horizontal pspInviaRPT initial XML pspInviaRPT
      | esitoComplessivoOperazione | identificativoCarrello | parametriPagamentoImmediato |
      | OK                         | $iuv                   | $iuv                        |
    And PSP replies to nodo-dei-pagamenti with the pspInviaRPT
    And from body with datatable vertical nodoInviaRPT initial XML nodoInviaRPT
      | identificativoIntermediarioPA         | #creditor_institution_code#  |
      | identificativoStazioneIntermediarioPA | #id_station#                 |
      | identificativoDominio                 | #creditor_institution_code#  |
      | identificativoUnivocoVersamento       | $iuv                         |
      | codiceContestoPagamento               | CCD01                        |
      | password                              | #password#                   |
      | identificativoPSP                     | #psp#                        |
      | identificativoIntermediarioPSP        | #psp#                        |
      | identificativoCanale                  | #canale_ATTIVATO_PRESSO_PSP# |
      | rpt                                   | $rptAttachment               |
    When EC sends SOAP nodoInviaRPT to nodo-dei-pagamenti
    Then check esito is KO of nodoInviaRPT response
    And check faultCode is PPT_SINTASSI_XSD of nodoInviaRPT response