Feature:  semantic checks for paVerifyPaymentNoticeRes

  Background:
    Given systems up   
    And PA new version
    And initial verifyPaymentNotice soap-request 
    And idChannel with USE_NEW_FAULT_CODE=Y
      """
      <soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:nod="http://pagopa-api.pagopa.gov.it/node/nodeForPsp.xsd">
         <soapenv:Header/>
         <soapenv:Body>
            <nod:verifyPaymentNoticeReq>
               <idPSP>70000000001</idPSP>
               <idBrokerPSP>70000000001</idBrokerPSP>
               <idChannel>70000000001_01</idChannel>
               <password>pwdpwdpwd</password>
               <qrCode>
                  <fiscalCode>#creditor_institution_code#</fiscalCode>
                  <noticeNumber>#notice_number#</noticeNumber>
               </qrCode>
            </nod:verifyPaymentNoticeReq>
         </soapenv:Body>
      </soapenv:Envelope>
      """

   
  Scenario Outline: Check PPT_ERRORE_EMESSO_DA_PAA error on fault generated by EC
    Given EC responds to nodo-dei-pagamenti at paVerifyPaymentNotice with:
        """
        <soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:paf="http://pagopa-api.pagopa.gov.it/pa/paForNode.xsd">
           <soapenv:Header/>
           <soapenv:Body>
              <paf:paVerifyPaymentNoticeRes>
                 <outcome>KO</outcome>
                 <fault>
                    <faultCode>PAA_SEMANTICA</faultCode>
                    <faultString>Errore semantico</faultString>
                    <id>1</id>
                 </fault>
              </paf:paVerifyPaymentNoticeRes>
           </soapenv:Body>
        </soapenv:Envelope>
        """
        When PSP sends verifyPaymentNoticeReq to nodo-dei-pagamenti
        Then check verifyPaymentNoticeRes outcome is KO
        And check verifyPaymentNoticeRes faultCode is PPT_ERRORE_EMESSO_DA_PAA
        And check verifyPaymentNoticeRes originalFaultCode is PAA_SEMANTICA
        And check verifyPaymentNoticeRes originalFaultString is 'Errore semantico'



 Scenario Outline: Check PPT_ERRORE_EMESSO_DA_PAA error on fault generated by EC when it isn't a known faultCode
    Given EC responds to nodo-dei-pagamenti at paVerifyPaymentNotice with:
        """
        <soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:paf="http://pagopa-api.pagopa.gov.it/pa/paForNode.xsd">
           <soapenv:Header/>
           <soapenv:Body>
              <paf:paVerifyPaymentNoticeRes>
                 <outcome>KO</outcome>
                 <fault>
                    <faultCode>PAA_CIAO</faultCode>
                    <faultString>Errore sconosciuto</faultString>
                    <id>1</id>
                 </fault>
              </paf:paVerifyPaymentNoticeRes>
           </soapenv:Body>
        </soapenv:Envelope>
        """
        When PSP sends verifyPaymentNoticeReq to nodo-dei-pagamenti
        Then check verifyPaymentNoticeRes outcome is KO
        And check verifyPaymentNoticeRes faultCode is PPT_ERRORE_EMESSO_DA_PAA
        And check verifyPaymentNoticeRes originalFaultCode is PAA_CIAO
        And check verifyPaymentNoticeRes originalFaultString is 'Errore sconosciuto'