Feature:  semantic checks for paVerifyPaymentNoticeRes faultCode

  Background:
    Given systems up 
    And initial verifyPaymentNotice soap-request 
    And idChannel with USE_NEW_FAULT_CODE=Y
      """
      <soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:nod="http://pagopa-api.pagopa.gov.it/node/nodeForPsp.xsd">
         <soapenv:Header/>
         <soapenv:Body>
            <nod:verifyPaymentNoticeReq>
               <idPSP>70000000001</idPSP>
               <idBrokerPSP>70000000001</idBrokerPSP>
               <idChannel>70000000001_01</idChannel>
               <password>pwdpwdpwd</password>
               <qrCode>
                  <fiscalCode>#creditor_institution_code#</fiscalCode>
                  <noticeNumber>#notice_number#</noticeNumber>
               </qrCode>
            </nod:verifyPaymentNoticeReq>
         </soapenv:Body>
      </soapenv:Envelope>
      """
      And EC new version
      
      
      Scenario Outline: Check PPT_ERRORE_EMESSO_DA_PAA error on fault generated by EC
    Given EC replies to nodo-dei-pagamenti with the following paVerifyPaymentNoticeRes:
        """
        <soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:paf="http://pagopa-api.pagopa.gov.it/pa/paForNode.xsd">
           <soapenv:Header/>
           <soapenv:Body>
              <paf:paVerifyPaymentNoticeRes>
                 <outcome>KO</outcome>
                 <fault>
                    <faultCode>#fault_code#</faultCode>
                    <faultString>#fault_string#</faultString>
                    <id>1</id>
                 </fault>
              </paf:paVerifyPaymentNoticeRes>
           </soapenv:Body>
        </soapenv:Envelope>
        """
        And faultCode with <faultCodeValue> in paVerifyPaymentNoticeRes
        And faultString with <faultStringValue> in paVerifyPaymentNoticeRes
        Examples:
      | faultCodeValue                        | faultStringValue                                           |
      | PAA_SINTASSI_EXTRAXSD                 | Errore di sintassi extra XSD.                              |
      | PAA_ID_DOMINIO_ERRATO                 | La PAA non corrisponde al Dominio indicato.                |
      | PAA_ID_INTERMEDIARIO_ERRATO           | Identificativo intermediario non corrispondente.           |
      | PAA_STAZIONE_INT_ERRATA               | Stazione intermediario non corrispondente.                 |
      | PAA_PAGAMENTO_SCONOSCIUTO             | Pagamento in attesa risulta sconosciuto all’Ente Creditore.|
      | PAA_PAGAMENTO_DUPLICATO               | Pagamento in attesa risulta concluso all’Ente Creditore.   |
      | PAA_PAGAMENTO_IN_CORSO                | Pagamento in attesa risulta in corso all’Ente Creditore.   |
      | PAA_PAGAMENTO_SCADUTO                 | Pagamento in attesa risulta scaduto all’Ente Creditore.    |
      | PAA_PAGAMENTO_ANNULLATO               | Pagamento in attesa risulta annullato all’Ente Creditore.  |
      | PAA_SYSTEM_ERROR                      | Errore generico.                                           |
            
      
        When PSP sends verifyPaymentNoticeReq to nodo-dei-pagamenti
        Then check verifyPaymentNoticeRes outcome is KO
        And check verifyPaymentNoticeRes faultCode is PPT_ERRORE_EMESSO_DA_PAA
        And check verifyPaymentNoticeRes originalFaultCode is <faultCodeValue>
        And check verifyPaymentNoticeRes originalFaultString is <faultStringValue>