Feature:  semantic checks for paVerifyPaymentNoticeRes faultCode

  Background:
    Given systems up
    And initial verifyPaymentNotice soap-request 
      """
      <soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:nod="http://pagopa-api.pagopa.gov.it/node/nodeForPsp.xsd">
         <soapenv:Header/>
         <soapenv:Body>
            <nod:verifyPaymentNoticeReq>
               <idPSP>70000000001</idPSP>
               <idBrokerPSP>70000000001</idBrokerPSP>
               <idChannel>70000000001_01</idChannel>
               <password>pwdpwdpwd</password>
               <qrCode>
                  <fiscalCode>#creditor_institution_code#</fiscalCode>
                  <noticeNumber>#notice_number#</noticeNumber>
               </qrCode>
            </nod:verifyPaymentNoticeReq>
         </soapenv:Body>
      </soapenv:Envelope>
      """
    And EC new version
    And idChannel with USE_NEW_FAULT_CODE=Y


  Scenario Outline: Check PPT_ERRORE_EMESSO_DA_PAA error on fault generated by EC
    Given EC replies to nodo-dei-pagamenti with the following paVerifyPaymentNoticeRes
      """
      <soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:paf="http://pagopa-api.pagopa.gov.it/pa/paForNode.xsd">
         <soapenv:Header/>
         <soapenv:Body>
            <paf:paVerifyPaymentNoticeRes>
               <outcome>KO</outcome>
               <fault>
                  <faultCode>#fault_code#</faultCode>
                  <faultString>#fault_string#</faultString>
                  <id>1</id>
               </fault>
            </paf:paVerifyPaymentNoticeRes>
         </soapenv:Body>
      </soapenv:Envelope>
      """
    And faultCode with <faultCodeValue> in paVerifyPaymentNoticeRes
    And faultString with <faultStringValue> in paVerifyPaymentNoticeRes
    When PSP sends verifyPaymentNoticeReq to nodo-dei-pagamenti
    Then check outcome is KO
    And check faultCode is PPT_ERRORE_EMESSO_DA_PAA
    And check originalFaultCode is <faultCodeValue>
    And check originalFaultString is <faultStringValue>
    Examples:
      | faultCodeValue              | faultStringValue                                            |
      | PAA_SINTASSI_EXTRAXSD       | Errore di sintassi extra XSD.                               |
      | PAA_ID_DOMINIO_ERRATO       | La PAA non corrisponde al Dominio indicato.                 |
      | PAA_ID_INTERMEDIARIO_ERRATO | Identificativo intermediario non corrispondente.            |
      | PAA_STAZIONE_INT_ERRATA     | Stazione intermediario non corrispondente.                  |
      | PAA_PAGAMENTO_SCONOSCIUTO   | Pagamento in_attesa risulta sconosciuto all Ente Creditore. |
      | PAA_PAGAMENTO_DUPLICATO     | Pagamento in_attesa risulta concluso all Ente Creditore.    |
      | PAA_PAGAMENTO_IN_CORSO      | Pagamento in_attesa risulta in_corso all Ente Creditore.    |
      | PAA_PAGAMENTO_SCADUTO       | Pagamento in_attesa risulta scaduto all Ente Creditore.     |
      | PAA_PAGAMENTO_ANNULLATO     | Pagamento in_attesa risulta annullato all Ente Creditore.   |
      | PAA_SYSTEM_ERROR            | Errore generico.                                            |

  # management of KO from PA - PRO_VPNR_06
  Scenario: Check PPT_ERRORE_EMESSO_DA_PAA error when paVerifyPaymentRes contains a KO
    Given EC replies to nodo-dei-pagamenti with the following paVerifyPaymentNoticeRes
    """
     <soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:paf="http://pagopa-api.pagopa.gov.it/pa/paForNode.xsd">
           <soapenv:Header/>
           <soapenv:Body>
              <paf:paVerifyPaymentNoticeRes>
                 <outcome>KO</outcome>
                 <fault>
                    <faultCode>PAA_SEMANTICA</faultCode>
                    <faultString>Errore semantico</faultString>
                    <id>1</id>
                 </fault>
              </paf:paVerifyPaymentNoticeRes>
           </soapenv:Body>
        </soapenv:Envelope>
    """
    When PSP sends verifyPaymentNoticeReq to nodo-dei-pagamenti
    Then check outcome is KO
    And check faultCode is PPT_ERRORE_EMESSO_DA_PAA

  # PA in timeout - PRO_VPNR_08
  Scenario: Check PPT_STAZIONE_INT_PA_TIMEOUT error when paVerifyPaymentRes is in timeout
    Given EC wait for 30 seconds at paVerifyPaymentNoticeRes
    When PSP sends verifyPaymentNoticeReq to nodo-dei-pagamenti
    Then check outcome is KO
    And check faultCode is PPT_STAZIONE_INT_PA_TIMEOUT
