version: '3.3'
services:
  # k6:
  #   image: grafana/k6
  #   # stdin_open: true # docker run -i
  #   # tty: true        # docker run -t      
  #   container_name: k6
  #   volumes:
  #     - '${PWD}/src:/scripts'
  #   environment:
  #     - K6_OUT=influxdb=http://nginx:8086/${db_name}
  #   command: run /scripts/perf-test/k6/scenarios/CT/test/TC01.03.js
  #   depends_on:
  #     - nginx

  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - '${PWD}/nginx/nginx.conf:/etc/nginx/nginx.conf'
    ports:
      - "8086:8086"
      - "80:80"

