trigger:
- master
pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.6'
- script: python -m pip install --upgrade pip
  displayName: 'Install dependencies'
- script: python3 -m pip install -r requirements.txt
  displayName: 'Install requirements'
- script: |
    behave --junit-directory=report --junit ./src/integ-test/bdd-test/features/NewMod3/primitives/{verifyPaymentNotice,activatePaymentNotice,sendPaymentOutcome}_syntax_ko.feature ./src/integ-test/bdd-test/features/appIO/primitives/activateIOPayment_syntax_ko.feature
    cd report && ls -l
  displayName: 'Run tests'
- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testResultsFiles: '**/report/*.xml'
    mergeTestResults: true
    testRunTitle: Integration test nodo-dei-pagamenti $(Date:yyyyMMdd)_$(Hour):$(Minutes):$(Seconds)