pr: none
trigger: none

pool:
  vmImage: 'ubuntu-latest'

parameters:
  - name: env
    displayName: Environment to deploy
    type: string
    default: prf
    values:
      - prf

variables:
  repository: 'mock-ec-prf'
  dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
  kustomizeFolderApp: '$(Build.SourcesDirectory)/kustomize'

stages:

  - stage: kubectl
    displayName: "kubectl"
    variables:
      - group: nodo-${{ parameters.env }}

    jobs:
      - job: retrieve_info
        displayName: "retrieve_info"
        pool: $(deploy-pool-${{ parameters.env }})
        steps:


          - script: |
              kubectl get pods -o wide -n mock-ec-prf
              kubectl get services  -o wide -n mock-ec-prf
              kubectl get ing -o json | jq -r '.items[].spec.rules[].http.paths[] -n mock-ec-prf
            displayName: "Retrieve Info in namespace"

