Feature: Semantic checks for paVerifyPaymentNoticeRes 1386

   Background:
      Given systems up


   @ALL @PRIMITIVE @NM3 @NM3PAVNRSSEMKO @NM3PAVNRSSEMKO_1 @after
   Scenario: Check PPT_ERRORE_EMESSO_DA_PAA error on fault generated by EC
      Given update for table INTERMEDIARI_PSP with parameter FAULT_BEAN_ESTESO = 'Y' on db nodo_cfg with where datatable horizontal
         | where_keys | where_values |
         | OBJ_ID     | 16646        |
      And waiting after triggered refresh job ALL
      And from body with datatable horizontal verifyPaymentNoticeBody_noOptional initial XML verifyPaymentNotice
         | idPSP | idBrokerPSP | idChannel                    | password   | fiscalCode                      | noticeNumber |
         | #psp# | #psp#       | #canale_ATTIVATO_PRESSO_PSP# | #password# | #creditor_institution_code_old# | 302#iuv#     |
      And from body with datatable vertical paVerifyPaymentNotice_KO initial XML paVerifyPaymentNotice
         | outcome     | KO               |
         | faultCode   | PAA_SEMANTICA    |
         | faultString | Errore semantico |
         | id          | 1                |
         | description | description      |
      And EC replies to nodo-dei-pagamenti with the paVerifyPaymentNotice
      When PSP sends SOAP verifyPaymentNotice to nodo-dei-pagamenti
      Then check outcome is KO of verifyPaymentNotice response
      And check faultCode is PPT_ERRORE_EMESSO_DA_PAA of verifyPaymentNotice response
      And check originalFaultCode is PAA_SEMANTICA of verifyPaymentNotice response
      And check originalFaultString is Errore semantico of verifyPaymentNotice response

