Feature: Syntax checks for verifyPaymentReq - KO 1402

  Background:
    Given systems up
    And initial XML verifyPaymentNotice
      """
      <soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:nod="http://pagopa-api.pagopa.gov.it/node/nodeForPsp.xsd">
      <soapenv:Header/>
      <soapenv:Body>
      <nod:verifyPaymentNoticeReq>
      <idPSP>#psp#</idPSP>
      <idBrokerPSP>#psp#</idBrokerPSP>
      <idChannel>#canale_ATTIVATO_PRESSO_PSP#</idChannel>
      <password>pwdpwdpwd</password>
      <qrCode>
      <fiscalCode>#creditor_institution_code#</fiscalCode>
      <noticeNumber>#notice_number#</noticeNumber>
      </qrCode>
      </nod:verifyPaymentNoticeReq>
      </soapenv:Body>
      </soapenv:Envelope>
      """

  @ALL @PRIMITIVE @NM3 @PG34
  # attribute value check
  Scenario Outline: Check PPT_SINTASSI_EXTRAXSD error on invalid wsdl namespace
    Given <attribute> set <value> for <elem> in verifyPaymentNotice
    When psp sends SOAP verifyPaymentNotice to nodo-dei-pagamenti
    Then check outcome is KO of verifyPaymentNotice response
    And check faultCode is PPT_SINTASSI_EXTRAXSD of verifyPaymentNotice response
    Examples:
      | elem             | attribute     | value                                     | soapUI test |
      | soapenv:Envelope | xmlns:soapenv | http://schemas.xmlsoap.org/ciao/envelope/ | SIN_VPNR_01 |

  @ALL @PRIMITIVE @NM3
  # element value check
  Scenario Outline: Check PPT_SINTASSI_EXTRAXSD error on invalid body element value
    Given <elem> with <value> in verifyPaymentNotice
    When psp sends SOAP verifyPaymentNotice to nodo-dei-pagamenti
    Then check outcome is KO of verifyPaymentNotice response
    And check faultCode is PPT_SINTASSI_EXTRAXSD of verifyPaymentNotice response
    Examples:
      | elem                       | value                                | soapUI test |
      | soapenv:Body               | None                                 | SIN_VPNR_02 |
      | soapenv:Body               | Empty                                | SIN_VPNR_03 |
      | nod:verifyPaymentNoticeReq | Empty                                | SIN_VPNR_04 |
      | idPSP                      | None                                 | SIN_VPNR_05 |
      | idPSP                      | Empty                                | SIN_VPNR_06 |
      | idPSP                      | 123456789012345678901234567890123456 | SIN_VPNR_07 |
      | idBrokerPSP                | None                                 | SIN_VPNR_08 |
      | idBrokerPSP                | Empty                                | SIN_VPNR_09 |
      | idBrokerPSP                | 123456789012345678901234567890123456 | SIN_VPNR_10 |
      | idChannel                  | None                                 | SIN_VPNR_11 |
      | idChannel                  | Empty                                | SIN_VPNR_12 |
      | idChannel                  | 123456789012345678901234567890123456 | SIN_VPNR_13 |
      | password                   | None                                 | SIN_VPNR_14 |
      | password                   | Empty                                | SIN_VPNR_15 |
      | password                   | 1234567                              | SIN_VPNR_16 |
      | password                   | 123456789012345678901234567890123456 | SIN_VPNR_17 |
      | qrCode                     | None                                 | SIN_VPNR_18 |
      | qrCode                     | RemoveParent                         | SIN_APNR_19 |
      | qrCode                     | Empty                                | SIN_VPNR_20 |
      | fiscalCode                 | None                                 | SIN_VPNR_21 |
      | fiscalCode                 | Empty                                | SIN_VPNR_22 |
      | fiscalCode                 | 1234567890                           | SIN_VPNR_23 |
      | fiscalCode                 | 123456789012                         | SIN_VPNR_24 |
      | fiscalCode                 | 12345jh%lk9                          | SIN_VPNR_25 |
      | noticeNumber               | None                                 | SIN_VPNR_26 |
      | noticeNumber               | Empty                                | SIN_VPNR_27 |
      | noticeNumber               | 12345678901234567                    | SIN_VPNR_28 |
      | noticeNumber               | 1234567890123456789                  | SIN_VPNR_28 |
      | noticeNumber               | 12345678901234567A                   | SIN_VPNR_29 |
      | noticeNumber               | 12345678901234567!                   | SIN_VPNR_29 |



  @ALL @PRIMITIVE @NM3 @prova
  Scenario Outline: Check PPT_ERRORE_EMESSO_DA_PAA error on fault generated by EC
    Given update through the query param_update_in of the table INTERMEDIARI_PSP the parameter FAULT_BEAN_ESTESO with Y, with where condition OBJ_ID and where value ('16646') under macro update_query on db nodo_cfg
    And refresh job ALL triggered after 10 seconds
    And initial XML verifyPaymentNotice
      """
      <soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:nod="http://pagopa-api.pagopa.gov.it/node/nodeForPsp.xsd">
      <soapenv:Header/>
      <soapenv:Body>
      <nod:verifyPaymentNoticeReq>
      <idPSP>#psp#</idPSP>
      <idBrokerPSP>#psp#</idBrokerPSP>
      <idChannel>#canale_ATTIVATO_PRESSO_PSP#</idChannel>
      <password>pwdpwdpwd</password>
      <qrCode>
      <fiscalCode>#creditor_institution_code#</fiscalCode>
      <noticeNumber>#notice_number#</noticeNumber>
      </qrCode>
      </nod:verifyPaymentNoticeReq>
      </soapenv:Body>
      </soapenv:Envelope>
      """
    And initial XML paVerifyPaymentNotice
      """
      <soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:paf="http://pagopa-api.pagopa.gov.it/pa/paForNode.xsd">
      <soapenv:Header/>
      <soapenv:Body>
      <paf:paVerifyPaymentNoticeRes>
      <outcome>KO</outcome>
      <fault>
      <faultCode>#faultCode#</faultCode>
      <faultString>#faultString#</faultString>
      <id>1</id>
      </fault>
      </paf:paVerifyPaymentNoticeRes>
      </soapenv:Body>
      </soapenv:Envelope>
      """
    And faultCode with <faultCodeValue> in paVerifyPaymentNotice
    And faultString with <faultStringValue> in paVerifyPaymentNotice
    And EC replies to nodo-dei-pagamenti with the paVerifyPaymentNotice
    When PSP sends SOAP verifyPaymentNotice to nodo-dei-pagamenti
    Then check outcome is KO of verifyPaymentNotice response
    And check faultCode is PPT_ERRORE_EMESSO_DA_PAA of verifyPaymentNotice response
    And check originalFaultCode is <faultCodeValue> of verifyPaymentNotice response
    And check originalFaultString is <faultStringValue> of verifyPaymentNotice response
    Examples:
      | faultCodeValue              | faultStringValue                                            |
      | PAA_SINTASSI_EXTRAXSD       | Errore di sintassi extra XSD.                               |
      | PAA_ID_DOMINIO_ERRATO       | La PAA non corrisponde al Dominio indicato.                 |
      | PAA_ID_INTERMEDIARIO_ERRATO | Identificativo intermediario non corrispondente.            |
      | PAA_STAZIONE_INT_ERRATA     | Stazione intermediario non corrispondente.                  |
      | PAA_PAGAMENTO_SCONOSCIUTO   | Pagamento in_attesa risulta sconosciuto all Ente Creditore. |
      | PAA_PAGAMENTO_DUPLICATO     | Pagamento in_attesa risulta concluso all Ente Creditore.    |
      | PAA_PAGAMENTO_IN_CORSO      | Pagamento in_attesa risulta in_corso all Ente Creditore.    |
      | PAA_PAGAMENTO_SCADUTO       | Pagamento in_attesa risulta scaduto all Ente Creditore.     |
      | PAA_PAGAMENTO_ANNULLATO     | Pagamento in_attesa risulta annullato all Ente Creditore.   |
      | PAA_SYSTEM_ERROR            | Errore generico.                                            |
      | PAA_CIAO                    | Errore sconosciuto                                          |