Feature: Syntax checks for verifyPaymentReq - KO 1402

  Background:
    Given systems up


  @ALL @PRIMITIVE @NM3 @NM3VPNSNTOK @NM3VPNSNTOK_1
  # attribute value check
  Scenario Outline: Check PPT_SINTASSI_EXTRAXSD error on invalid wsdl namespace
    Given from body with datatable horizontal verifyPaymentNoticeBody_noOptional initial XML verifyPaymentNotice
      | idPSP | idBrokerPSP | idChannel                    | password   | fiscalCode                  | noticeNumber |
      | #psp# | #psp#       | #canale_ATTIVATO_PRESSO_PSP# | #password# | #creditor_institution_code# | 302#iuv#     |
    And <attribute> set <value> for <elem> in verifyPaymentNotice
    When psp sends SOAP verifyPaymentNotice to nodo-dei-pagamenti
    Then check outcome is KO of verifyPaymentNotice response
    And check faultCode is PPT_SINTASSI_EXTRAXSD of verifyPaymentNotice response
    Examples:
      | elem             | attribute     | value                                     | soapUI test |
      | soapenv:Envelope | xmlns:soapenv | http://schemas.xmlsoap.org/ciao/envelope/ | SIN_VPNR_01 |



  @ALL @PRIMITIVE @NM3 @NM3VPNSNTOK @NM3VPNSNTOK_2
  # element value check
  Scenario Outline: Check PPT_SINTASSI_EXTRAXSD error on invalid body element value
    Given from body with datatable horizontal verifyPaymentNoticeBody_noOptional initial XML verifyPaymentNotice
      | idPSP | idBrokerPSP | idChannel                    | password   | fiscalCode                  | noticeNumber |
      | #psp# | #psp#       | #canale_ATTIVATO_PRESSO_PSP# | #password# | #creditor_institution_code# | 302#iuv#     |
    Given <elem> with <value> in verifyPaymentNotice
    When psp sends SOAP verifyPaymentNotice to nodo-dei-pagamenti
    Then check outcome is KO of verifyPaymentNotice response
    And check faultCode is PPT_SINTASSI_EXTRAXSD of verifyPaymentNotice response
    Examples:
      | elem                       | value                                | soapUI test |
      | soapenv:Body               | None                                 | SIN_VPNR_02 |
      | soapenv:Body               | Empty                                | SIN_VPNR_03 |
      | nod:verifyPaymentNoticeReq | Empty                                | SIN_VPNR_04 |
      | idPSP                      | None                                 | SIN_VPNR_05 |
      | idPSP                      | Empty                                | SIN_VPNR_06 |
      | idPSP                      | 123456789012345678901234567890123456 | SIN_VPNR_07 |
      | idBrokerPSP                | None                                 | SIN_VPNR_08 |
      | idBrokerPSP                | Empty                                | SIN_VPNR_09 |
      | idBrokerPSP                | 123456789012345678901234567890123456 | SIN_VPNR_10 |
      | idChannel                  | None                                 | SIN_VPNR_11 |
      | idChannel                  | Empty                                | SIN_VPNR_12 |
      | idChannel                  | 123456789012345678901234567890123456 | SIN_VPNR_13 |
      | password                   | None                                 | SIN_VPNR_14 |
      | password                   | Empty                                | SIN_VPNR_15 |
      | password                   | 1234567                              | SIN_VPNR_16 |
      | password                   | 123456789012345678901234567890123456 | SIN_VPNR_17 |
      | qrCode                     | None                                 | SIN_VPNR_18 |
      | qrCode                     | RemoveParent                         | SIN_APNR_19 |
      | qrCode                     | Empty                                | SIN_VPNR_20 |
      | fiscalCode                 | None                                 | SIN_VPNR_21 |
      | fiscalCode                 | Empty                                | SIN_VPNR_22 |
      | fiscalCode                 | 1234567890                           | SIN_VPNR_23 |
      | fiscalCode                 | 123456789012                         | SIN_VPNR_24 |
      | fiscalCode                 | 12345jh%lk9                          | SIN_VPNR_25 |
      | noticeNumber               | None                                 | SIN_VPNR_26 |
      | noticeNumber               | Empty                                | SIN_VPNR_27 |
      | noticeNumber               | 12345678901234567                    | SIN_VPNR_28 |
      | noticeNumber               | 1234567890123456789                  | SIN_VPNR_28 |
      | noticeNumber               | 12345678901234567A                   | SIN_VPNR_29 |
      | noticeNumber               | 12345678901234567!                   | SIN_VPNR_29 |



  @ALL @PRIMITIVE @NM3 @NM3VPNSNTOK @NM3VPNSNTOK_3 @after
  Scenario Outline: Check PPT_ERRORE_EMESSO_DA_PAA error on fault generated by EC
    Given update for table INTERMEDIARI_PSP with parameter FAULT_BEAN_ESTESO = 'Y' on db nodo_cfg with where datatable horizontal
      | where_keys | where_values |
      | OBJ_ID     | 16646        |
    And waiting after triggered refresh job ALL
    And from body with datatable horizontal verifyPaymentNoticeBody_noOptional initial XML verifyPaymentNotice
      | idPSP | idBrokerPSP | idChannel                    | password   | fiscalCode                  | noticeNumber |
      | #psp# | #psp#       | #canale_ATTIVATO_PRESSO_PSP# | #password# | #creditor_institution_code# | 302#iuv#     |
    And from body with datatable vertical paVerifyPaymentNotice_KO initial XML paVerifyPaymentNotice
      | outcome     | KO            |
      | faultCode   | #faultCode#   |
      | faultString | #faultString# |
      | id          | 1             |
    And faultCode with <faultCodeValue> in paVerifyPaymentNotice
    And faultString with <faultStringValue> in paVerifyPaymentNotice
    And EC replies to nodo-dei-pagamenti with the paVerifyPaymentNotice
    When PSP sends SOAP verifyPaymentNotice to nodo-dei-pagamenti
    Then check outcome is KO of verifyPaymentNotice response
    And check faultCode is PPT_ERRORE_EMESSO_DA_PAA of verifyPaymentNotice response
    And check originalFaultCode is <faultCodeValue> of verifyPaymentNotice response
    And check originalFaultString is <faultStringValue> of verifyPaymentNotice response
    Examples:
      | faultCodeValue              | faultStringValue                                            |
      | PAA_SINTASSI_EXTRAXSD       | Errore di sintassi extra XSD.                               |
      | PAA_ID_DOMINIO_ERRATO       | La PAA non corrisponde al Dominio indicato.                 |
      | PAA_ID_INTERMEDIARIO_ERRATO | Identificativo intermediario non corrispondente.            |
      | PAA_STAZIONE_INT_ERRATA     | Stazione intermediario non corrispondente.                  |
      | PAA_PAGAMENTO_SCONOSCIUTO   | Pagamento in_attesa risulta sconosciuto all Ente Creditore. |
      | PAA_PAGAMENTO_DUPLICATO     | Pagamento in_attesa risulta concluso all Ente Creditore.    |
      | PAA_PAGAMENTO_IN_CORSO      | Pagamento in_attesa risulta in_corso all Ente Creditore.    |
      | PAA_PAGAMENTO_SCADUTO       | Pagamento in_attesa risulta scaduto all Ente Creditore.     |
      | PAA_PAGAMENTO_ANNULLATO     | Pagamento in_attesa risulta annullato all Ente Creditore.   |
      | PAA_SYSTEM_ERROR            | Errore generico.                                            |
      | PAA_CIAO                    | Errore sconosciuto                                          |