pr: none
trigger: none

pool:
  vmImage: 'ubuntu-latest'

parameters:
  - name: env
    displayName: Environment to Run Test
    type: string
    values:
      - dev
      - sit

#variables:


stages:
  - stage: retrieve_testsuite
    displayName: "Fetch Test Suite (${{ parameters.env }})"
    variables:
      - group: nodo-${{ parameters.env }}   
    jobs:
      - job: execute
        displayName: "Execute Test Suite (${{ parameters.env }})"
        pool: $(deploy-pool-${{ parameters.env }})
        steps:
          - checkout: none

          - script: |
              pwd
              ls -la