trigger:
- master
pool:
  vmImage: 'ubuntu-latest'

name: '$(Date:yyyy-MM-dd)$(Rev:.rr)'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.6'
- script: python -m pip install --upgrade pip
  displayName: 'Install dependencies'
- script: |
    sudo apt-get install build-essential unzip
    cd /opt/
    sudo mkdir /opt/oracle
    sudo wget https://download.oracle.com/otn_software/linux/instantclient/216000/instantclient-basic-linux.x64-21.6.0.0.0dbru.zip
    sudo unzip instantclient-basic-linux.x64-21.6.0.0.0dbru.zip
    sudo apt update
    sudo apt install libaio1
    sudo sh -c "echo /opt/oracle/instantclient-basic-linux.x64-21.6.0.0.0dbru > /etc/ld.so.conf.d/oracle-instantclient.conf"
    sudo ldconfig
  displayName: 'Install Oracle Instant Client'
- script: python3 -m pip install -r requirements.txt
  displayName: 'Install requirements'
- script: |
    behave --junit-directory=report --junit ./features/NewMod3/flows/TestGenerazioneRicevute03/generazioneRicevute_flows_ko_PAnew.feature
  displayName: 'Run tests'
- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testResultsFiles: '**/report/*.xml'
    mergeTestResults: true
    testRunTitle: Integration test payment-manager $(Build.BuildNumber)
    failTaskOnFailedTests: true
