pr: none
trigger: none

pool:
  vmImage: 'ubuntu-latest'

parameters:
  - name: env
    displayName: Environment to Run Test
    type: string
    values:
      - dev
      - sit

variables:
  artifactName: TestSuite


  

stages:
  - stage: python_env
    displayName: "Fetch Test Suite (${{ parameters.env }})"
    jobs:
      - job: 
        displayName: "python_env (${{ parameters.env }})"
        steps:
          - checkout: self
            clean: true
            persistCredentials: true
            
            
          - task: UsePythonVersion@0
            displayName: 'Use Python 3.x'
            inputs:
              versionSpec: '3.10'


          - task: ArchiveFiles@2
            displayName: 'Archive files'
            inputs:
              rootFolderOrFile: /home/vsts/work/1/s/
              includeRootFolder: false
              archiveType: zip
              archiveFile: $(Build.ArtifactStagingDirectory)/nodo-dei-pagamenti-NRT.zip
              replaceExistingArchive: true

            
          - publish: $(Build.ArtifactStagingDirectory)/nodo-dei-pagamenti-NRT.zip
            displayName: "Publish Virtual Enviroment"
            artifact: $(artifactName)
            
            
  - stage: test_execute
    displayName: "Execute Test Suite (${{ parameters.env }})"
    dependsOn:
      - python_env
    variables:
      - group: nodo-${{ parameters.env }}
    condition: succeeded()
    jobs:
      - job: test_execute
        displayName: "execute test suite (${{ parameters.env }})"
        pool: $(deploy-pool-${{ parameters.env }})
        steps:
          - checkout: none
          
          - download: current
            artifact: $(artifactName)
            displayName: "Download Test Suite"
            
            # Download an artifact named 'WebApp' to 'bin' in $(Build.SourcesDirectory)
          - task: DownloadPipelineArtifact@2
            inputs:
              artifact: $(artifactName)
              path: /agent/_work/1
              source: current

          - script: |
             
             pwd
             echo "/agent/_work/1"
             ls -la /agent/_work/1

             echo "/agent/_work/1/TestSuite"
             ls -la /agent/_work/1/TestSuite
                          
            displayName: 'Install requirements using pip'

          - task: ExtractFiles@1
            inputs:
              archiveFilePatterns: /agent/_work/1/TestSuite/nodo-dei-pagamenti-NRT.zip
              destinationFolder: '$(System.ArtifactsDirectory)/extracted'
              cleanDestinationFolder: true
              overwriteExistingFiles: false

          - script: |
              sudo apt-get install build-essential unzip
              mkdir /agent/_work/1/a/extracted/oracle
              cd /agent/_work/1/a/extracted/oracle
              sudo wget https://download.oracle.com/otn_software/linux/instantclient/216000/instantclient-basic-linux.x64-21.6.0.0.0dbru.zip
              sudo unzip instantclient-basic-linux.x64-21.6.0.0.0dbru.zip
              sudo apt update
              sudo apt install libaio1
              sudo sh -c "echo /agent/_work/1/a/extracted/oracle/instantclient_21_6 > /etc/ld.so.conf.d/oracle-instantclient.conf"
              sudo ldconfig
            displayName: 'Install Oracle Instant Client'


          - script: |
             
             whereis python3
             sudo python3 -m pip3 install -r /agent/_work/1/a/extracted/requirements.txt
             #sudo pip3 install behave
             whereis behave
             
             
            displayName: 'Install requirements using pip'
              


