pr: none
trigger: none

pool:
  vmImage: 'ubuntu-latest'

parameters:
  - name: env
    displayName: Environment to Run Test
    type: string
    values:
      - dev
      - sit

variables:
  artifactName: TestSuite
  artifactDownloadedPath: /agent/_work/nrt
  destinationFolderExtractArtifact: nodo/extracted
  deploy-pool: nodopagamenti-agent-pool-sit


  

stages:
  - stage: python_env
    displayName: "Fetch Test Suite (${{ parameters.env }})"
    jobs:
      - job: 
        displayName: "python_env (${{ parameters.env }})"
        steps:
          - checkout: self
            clean: true
            persistCredentials: true
            
            
          - task: UsePythonVersion@0
            displayName: 'Use Python 3.x'
            inputs:
              versionSpec: '3.10'

          - script: |
              sudo apt-get install build-essential unzip
              mkdir $(Agent.BuildDirectory)/s/oracle
              cd $(Agent.BuildDirectory)/s/oracle
              sudo wget https://download.oracle.com/otn_software/linux/instantclient/216000/instantclient-basic-linux.x64-21.6.0.0.0dbru.zip
              sudo unzip instantclient-basic-linux.x64-21.6.0.0.0dbru.zip
              sudo apt update
              sudo apt install libaio1
              #sudo sh -c "echo /agent/_work/1/a/extracted/oracle/instantclient_21_6 > /etc/ld.so.conf.d/oracle-instantclient.conf"
              #sudo ldconfig
            displayName: 'Install Oracle Instant Client'


          - task: ArchiveFiles@2
            displayName: 'Archive files'
            inputs:
              rootFolderOrFile: $(Agent.BuildDirectory)/s/
              includeRootFolder: false
              archiveType: zip
              archiveFile: $(Build.ArtifactStagingDirectory)/nodo-dei-pagamenti-NRT.zip
              replaceExistingArchive: true

            
          - publish: $(Build.ArtifactStagingDirectory)/nodo-dei-pagamenti-NRT.zip
            displayName: "Publish Artifact"
            artifact: $(artifactName)
            
            
  - stage: test_execute
    displayName: "Execute Test Suite (${{ parameters.env }})"
    dependsOn:
      - python_env
    condition: succeeded()
    jobs:
      - job: test_execute
        timeoutInMinutes: 0 # how long to run the job before automatically cancelling. When 0 is specified, the maximum limit is used
        displayName: "execute test suite (${{ parameters.env }})"
        pool: $(deploy-pool)
        steps:
          - checkout: none          

          - task: DownloadPipelineArtifact@2
            inputs:
              artifact: $(artifactName)
              source: current
          - task: ExtractFiles@1
            inputs:
              archiveFilePatterns: $(Pipeline.Workspace)/nodo-dei-pagamenti-NRT.zip
              destinationFolder: $(Pipeline.Workspace)/$(destinationFolderExtractArtifact)
              cleanDestinationFolder: true
              overwriteExistingFiles: false
          - script: |
              echo $(Pipeline.Workspace)
              echo $(Pipeline.Workspace)/$(destinationFolderExtractArtifact)/oracle/instantclient_21_6
              sudo sh -c "echo $(Pipeline.Workspace)/$(destinationFolderExtractArtifact)/oracle/instantclient_21_6 > /etc/ld.so.conf.d/oracle-instantclient.conf"
              sudo ldconfig
            displayName: 'Linux ldconfig Command for Oracle Instant Client'
          - script: |
             whereis python3
             whereis pip3
             whereis pip
             echo $PATH
             
             export PATH=/usr/bin:/usr/local/bin:$PATH #Add environment variables
             echo $PATH

             which python3
             which pip3
             which pip
             
             sudo pip3 install behave 
             sudo pip3 install -U -r $(Pipeline.Workspace)/$(destinationFolderExtractArtifact)/requirements.txt #Install Requirements
             whereis behave
             which behave

             #behave --help #Run behave

             # Damiano
             #behave --junit-directory=$(Pipeline.Workspace)/$(destinationFolderExtractArtifact)/report --junit $(Pipeline.Workspace)/$(destinationFolderExtractArtifact)/src/integ-test/bdd-test/features/RTPull/RTPull_flows.feature --tags=ok
             
             # Nicolò
             #behave --junit-directory=$(Pipeline.Workspace)/$(destinationFolderExtractArtifact)/report --junit $(Pipeline.Workspace)/$(destinationFolderExtractArtifact)/src/integ-test/bdd-test/features/NewMod3/flows/verificaBollettinoEPoste/verificaBollettino_TF_POSTE_05.feature
             
             # Lorenzo  
             behave --junit-directory=$(Pipeline.Workspace)/$(destinationFolderExtractArtifact)/report --junit $(Pipeline.Workspace)/$(destinationFolderExtractArtifact)/src/integ-test/bdd-test/features/NewMod3/flows/paSendRT/PSRT_27.feature
             
             # Alessandro
             #behave --junit-directory=$(Pipeline.Workspace)/$(destinationFolderExtractArtifact)/report --junit $(Pipeline.Workspace)/$(destinationFolderExtractArtifact)/src/integ-test/bdd-test/features/appIO/primitives/pspNotifyPaymentResponse_syntax_ko.feature
             
             # Marisa
             #behave --junit-directory=$(Pipeline.Workspace)/$(destinationFolderExtractArtifact)/report --junit $(Pipeline.Workspace)/$(destinationFolderExtractArtifact)/src/integ-test/bdd-test/features/NewMod3/flows/activatePaymentNotice/PRO_APNR_07.feature
             

             # Redis
             #behave --junit-directory=$(Pipeline.Workspace)/$(destinationFolderExtractArtifact)/report --junit $(Pipeline.Workspace)/$(destinationFolderExtractArtifact)/src/integ-test/bdd-test/features/NewMod3/flows/verifyPaymentNotice/PRO_VPNR_07.feature
             
             # Gabriel
             



            displayName: 'Run Behave Test Suite'
          - task: PublishTestResults@2
            condition: succeededOrFailed()
            inputs:
              testResultsFiles: '$(Pipeline.Workspace)/$(destinationFolderExtractArtifact)/report/*.xml'
              mergeTestResults: true
              testRunTitle: Integration test Nodo $(Build.BuildNumber)
              failTaskOnFailedTests: true
          - script: |
             sudo rm -rf $(Pipeline.Workspace)/*
             
            displayName: 'Agent Pool CleanUP'