pr: none
trigger: none

pool:
  vmImage: 'ubuntu-latest'

#parameters:
#  - name: env
#    displayName: Environment to Run Test
#    type: string
#    values:
#      - dev
#      - sit

#variables:
  #repository: 'mock-ec'
  #dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
  #kustomizeFolderApp: '$(Build.SourcesDirectory)/kustomize-mock-ec'

stages:
  - stage: retrieve_testsuite
    displayName: "Fetch Test Suite"
    jobs:
      - job: 
        displayName: "Retrieve Test Suite"
        steps:
          - checkout: self
            clean: true
            persistCredentials: true
            path: $(Agent.BuildDirectory)/s
          - publish: $(Agent.BuildDirectory)/s
            displayName: "Publish Behave Test Suite"
            artifact: TestSuite