pr: none
trigger: none

pool:
  vmImage: 'ubuntu-latest'

parameters:
  - name: env
    displayName: Environment to Run Test
    type: string
    values:
      - dev
      - sit

variables:

  nodopath: /home/vsts/work/1/s/pagopa-nodo-dei-pagamenti-test
  

stages:
  - stage: python_env
    displayName: "Fetch Test Suite (${{ parameters.env }})"
    jobs:
      - job: 
        displayName: "python_env"
        steps:
          - checkout: self
            clean: true
            persistCredentials: true
            
            
          - task: UsePythonVersion@0
            displayName: 'Use Python 3.x'
            inputs:
              versionSpec: '3.10'
            
          - script: |
              sudo apt install python3-venv
              cd $(nodopath)
              python3 -m venv env
              source ./env/bin/activate
            displayName: 'Create Virtual Environment  (${{ parameters.env }})'
            
          - script: |
              sudo apt-get install build-essential unzip
              cd ./env
              sudo mkdir oracle
              cd oracle
              sudo wget https://download.oracle.com/otn_software/linux/instantclient/216000/instantclient-basic-linux.x64-21.6.0.0.0dbru.zip
              sudo unzip instantclient-basic-linux.x64-21.6.0.0.0dbru.zip
              sudo apt update
              sudo apt install libaio1
            displayName: 'Install Oracle Instant Client (${{ parameters.env }})'
            
          - script: |
             pwd
             ls -la
             python3 -m pip install -r requirements.txt
             cd ./env
             ls -la
             pwd
            displayName: 'Install requirements (${{ parameters.env }})'

          - task: ArchiveFiles@2
            displayName: 'Archive files (${{ parameters.env }})'
            inputs:
              rootFolderOrFile: /home/vsts/work/1/s/
              includeRootFolder: false
              archiveType: zip
              archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
              replaceExistingArchive: true

            
          - publish: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
            displayName: "Publish Virtual Enviroment (${{ parameters.env }})"
            artifact: TestSuite
            
            
  - stage: test_execute
    displayName: "Execute Test Suite (${{ parameters.env }})"
    dependsOn:
      - python_env
    variables:
      - group: nodo-${{ parameters.env }}
    condition: succeeded()
    jobs:
      - job: test_execute
        displayName: "execute test suite (${{ parameters.env }})"
        pool: $(deploy-pool-${{ parameters.env }})
        steps:
          - checkout: none
          
          - download: current
            artifact: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
            displayName: "Download Test Suite $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip"
            
          
          - task: ExtractFiles@1
            inputs:
              archiveFilePatterns: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
              cleanDestinationFolder: true
              overwriteExistingFiles: false
              
          - script: |
             pwd
             ls -la
             
            displayName: 'After Extracting Archive'