trigger:
- master
pool:
  vmImage: 'ubuntu-latest'

name: '$(Date:yyyy-MM-dd)$(Rev:.rr)'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.6'
- script: python -m pip install --upgrade pip
  displayName: 'Install dependencies'
- script: python3 -m pip install -r requirements.txt
  displayName: 'Install requirements'
- script: |
    behave --junit-directory=report --junit ./src/integ-test/bdd-test/features/NewMod3/primitives/activatePaymentNotice_syntax_ok.feature
  displayName: 'Run tests'
- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testResultsFiles: '**/report/*.xml'
    mergeTestResults: true
    testRunTitle: Integration test nodo-dei-pagamenti $(Build.BuildNumber)
    failTaskOnFailedTests: true