pr: none
trigger: none

pool:
  vmImage: 'ubuntu-latest'

parameters:
  - name: env
    displayName: Environment to Run Test
    type: string
    values:
      - dev
      - sit

variables:
  artifactName: TestSuite
  destinationFolderExtractArtifact: payment-manager/extracted
  pm-agent-pool-sit: pm-agent-pool-sit #Per Sit


  

stages:
  - stage: python_env
    displayName: "Fetch Test Suite (${{ parameters.env }})"
    jobs:
      - job: 
        displayName: "python_env (${{ parameters.env }})"
        steps:
          - checkout: self
            clean: true
            persistCredentials: true
            
            
          - task: UsePythonVersion@0
            displayName: 'Use Python 3.x'
            inputs:
              versionSpec: '3.10'

          - script: |
              
              sudo apt-get install build-essential unzip
              echo $(Agent.BuildDirectory)
              mkdir $(Agent.BuildDirectory)/s/oracle
              cd $(Agent.BuildDirectory)/s/oracle
              sudo wget https://download.oracle.com/otn_software/linux/instantclient/216000/instantclient-basic-linux.x64-21.6.0.0.0dbru.zip
              sudo unzip instantclient-basic-linux.x64-21.6.0.0.0dbru.zip
              sudo apt update
              sudo apt install libaio1
            displayName: 'Install Oracle Instant Client'


          - task: ArchiveFiles@2
            displayName: 'Archive files'
            inputs:
              rootFolderOrFile: $(Agent.BuildDirectory)/s/
              includeRootFolder: false
              archiveType: zip
              archiveFile: $(Build.ArtifactStagingDirectory)/payment-manager-NRT.zip
              replaceExistingArchive: true

            
          - publish: $(Build.ArtifactStagingDirectory)/payment-manager-NRT.zip
            displayName: "Publish Artifact"
            artifact: $(artifactName)
            
            
  - stage: test_execute
    displayName: "Execute Test Suite (${{ parameters.env }})"
    dependsOn:
      - python_env
    
    condition: succeeded()
    jobs:
      - job: test_execute
        displayName: "execute test suite (${{ parameters.env }})"
        pool: $(pm-agent-pool-sit)
        steps:
          - checkout: none          

          - task: DownloadPipelineArtifact@2
            inputs:
              artifact: $(artifactName)
              source: current
          - task: ExtractFiles@1
            inputs:
              archiveFilePatterns: $(Pipeline.Workspace)/payment-manager-NRT.zip
              destinationFolder: $(Pipeline.Workspace)/$(destinationFolderExtractArtifact)
              cleanDestinationFolder: true
              overwriteExistingFiles: false


              
          - script: |
              echo $(Pipeline.Workspace)
              echo $(Pipeline.Workspace)/$(destinationFolderExtractArtifact)/oracle/instantclient_21_6
              sudo sh -c "echo $(Pipeline.Workspace)/$(destinationFolderExtractArtifact)/oracle/instantclient_21_6 > /etc/ld.so.conf.d/oracle-instantclient.conf"
              sudo ldconfig
            displayName: 'Linux ldconfig Command for Oracle Instant Client'
          - script: |
             echo "==== Add python3 and pip3 in PATH var==== "
             echo $PATH
             export PATH=/usr/bin:/usr/local/bin:$PATH 
             echo $PATH
             
             echo "==== install behave ==== "
             sudo pip3 install behave
             
             echo "==== install python dependencies...==== "
             echo $(Pipeline.Workspace)/$(destinationFolderExtractArtifact)
             sudo pip3 install -U -r $(Pipeline.Workspace)/$(destinationFolderExtractArtifact)/requirements.txt
             
             "==== install selenium...==== "
             sudo pip3 install selenium
             sudo pip3 install cx-Oracle
             
             "==== Check packages installed...==== "
             pip3 list
             
             "==== Behave Test Suite...==== "
             ls -R /usr/local/lib/python3.6/site-packages
             ls -la /usr/local/lib/python3.6/site-packages

             export PYTHONPATH=$PYTHONPATH:$(Pipeline.Workspace)/$(destinationFolderExtractArtifact)

             behave --junit-directory=$(Pipeline.Workspace)/$(destinationFolderExtractArtifact)/report --junit $(Pipeline.Workspace)/$(destinationFolderExtractArtifact)/features/3DS/15_3ds.feature


            displayName: 'Run Behave Test Suite'
          - task: PublishTestResults@2
            condition: succeededOrFailed()
            inputs:
              testResultsFiles: '$(Pipeline.Workspace)/$(destinationFolderExtractArtifact)/report/*.xml'
              mergeTestResults: true
              testRunTitle: Integration Test Payment Manager $(Build.BuildNumber)
              failTaskOnFailedTests: true
          - script: |
             sudo rm -rf $(Pipeline.Workspace)/*
             
            displayName: 'Agent Pool CleanUP'