pr: none
trigger: none

pool:
  vmImage: 'ubuntu-latest'

  

stages:
           
            
  - stage: k6_installation_check
    displayName: "K6 Installation Check"

    jobs:
      - job: k6_version_check
        displayName: "k6_version_check"
        pool: pagopa-agent-pool-uat
        steps:
          - checkout: none    
          - script: |
             hostname
             whereis k6
             k6 version