pool:

  name: pagopa-agent-pool-uat

steps:

- script: |
   echo pwd
   pwd
   
   echo ls -lrt
   ls -lrt
   
   echo hostname:
   hostname
   
   echo whereis k6
   whereis k6
   
   echo whereis git
   whereis git
   
   echo k6 version
   k6 version
   

  displayName: 'Command Line Script'



- script: |
   echo current dir:
   pwd
   
   echo ---------- git clone start ----------
   git clone --branch test-accenture-perftest https://github.com/pagopa/pagopa-nodo-dei-pagamenti-test.git
   echo ---------- git clone end ----------
   
   echo ----------  list start ----------
   ls -lrt
   echo ---------- list end ----------
   

  displayName: 'Command Line Script - git clone'



- script: |
   active_scenario=PMCS_CT
   active_test=TC01.01
   test_step=rampa_1_1_10
   
   ###### env must match with one of line of cfg/baseUrl_PM.csv #############
   env="pagoPA_DEV_apim"
   
   echo -----------------------------------------
   echo *** Main K6 Perf Test Script ***
   echo -----------------------------------------
   
   echo configured active_scenario = $active_scenario
   echo configured active_test = $active_test
   echo configured test_step= $test_step
   echo configured env= $env
   
   cd pagopa-nodo-dei-pagamenti-test/src/perf-test/k6
   
   sh './scenarios/'$active_scenario'/test_selector.sh' $active_scenario $active_test $test_step $env

  displayName: 'Command Line Script - Run CT - TC03.05 - rampa_1_1_10'



- script: |
   echo ---------- RESULTS ---------- 
   
   echo current dir:
   pwd
   
   echo active scenario: $active_scenario
   
   cd scenarios/$active_scenario/test/output/
   
   echo pwd
   pwd
   
   cat *
   
   echo ---------- END ---------- 
   

  displayName: 'Command Line Script - show results'



- script: |
   echo ---------- removing files ---------- 
   
   echo current dir
   pwd
   
   cd ~
   
   rm -rf pagopa-nodo-dei-pagamenti-test
   
   echo list:
   ls -lrt
   echo ---------- END ---------- 
   

  displayName: 'Command Line Script - remove files'

  condition: always()



