pool:

  name: pagopa-agent-pool-uat

steps:
- checkout: none
- script: |
   echo pwd
   pwd
   
   echo ls -lrt
   ls -lrt
   
   echo hostname:
   hostname
   
   echo whereis k6
   whereis k6
   
   echo whereis git
   whereis git
   
   echo k6 version
   k6 version
   

  displayName: 'Command Line Script'