pr: none
trigger: none

pool:
  vmImage: 'ubuntu-latest'

parameters:
  - name: env
    displayName: Environment to Run Test
    type: string
    values:
      - prf

variables:
  artifactName: TestPT
  activeScenario: PMCS_CT

stages:
  
  - stage: publish_artifact
    displayName: "Publish artifact env (${{ parameters.env }})"
    jobs:
      - job: 
        displayName: "publish artifact on env (${{ parameters.env }})"
        steps:
          - checkout: self
            clean: true
            persistCredentials: true
                      
          - task: ArchiveFiles@2
            displayName: 'Archive files'
            inputs:
              rootFolderOrFile: $(Agent.BuildDirectory)/
              includeRootFolder: false
              archiveType: zip
              archiveFile: $(Build.ArtifactStagingDirectory)/pagopa-nodo-dei-pagamenti-test.zip
              replaceExistingArchive: true
            
          - publish: $(Build.ArtifactStagingDirectory)/pagopa-nodo-dei-pagamenti-test.zip
            displayName: "Publish Artifact"
            artifact: $(artifactName)
            
            
  - stage: k6_installation_check
    displayName: "K6 Installation Check"

    jobs:
      - job: k6_run_scripts
        displayName: "k6 run scripts"
        pool: pagopa-agent-pool-uat
        
        steps:
          - checkout: none    
                       
          - task: DownloadPipelineArtifact@2
            inputs:
              artifact: $(artifactName)
              source: current
          
          - task: ExtractFiles@1
            inputs:
              archiveFilePatterns: $(Pipeline.Workspace)/pagopa-nodo-dei-pagamenti-test.zip
              destinationFolder: $(Pipeline.Workspace)
              cleanDestinationFolder: false
              overwriteExistingFiles: true
                        
          - script: |
              active_scenario=$(activeScenario)
              active_test=TC01.01
              test_step=rampa_1_1_10
   
              env="pagoPA_PERF_apim"
          
              echo -----------------------------------------
              echo *** Main K6 Perf Test Script ***
              echo -----------------------------------------
             
              echo configured active_scenario = $active_scenario
              echo configured active_test = $active_test
              echo configured test_step= $test_step
              echo configured env= $env
             
              cd src/perf-test/k6
             
              sh './scenarios/'$active_scenario'/test_selector.sh' $active_scenario $active_test $test_step $env
            displayName: 'Command Line Script - Run CT - TC03.05 - rampa_1_1_10'
          
          - script: |
             echo pwd:
             pwd
             echo list:
             ls -lrt
             echo changind dir to go in output...
             cd src/perf-test/k6/scenarios/$(activeScenario)/test/output
             echo pwd after changing dir:
             pwd
             echo list:
             ls -lrt
             
             echo start cat
             cat *
             echo end cat
            displayName: 'show results'
            