{{- $namespace := .Values.namespace }}
{{- range .Values.secrets }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
    name: {{ .name }}
    namespace: {{ $namespace }}
    annotations:
      sealedsecrets.bitnami.com/cluster-wide: "true"
spec:
  encryptedData:
    username: {{ .username }}
    password: {{ .password }}
  template:
    metadata:
      creationTimestamp: null
      name: {{ .name }}
      namespace: {{ $namespace }}
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
    type: Opaque
---
{{- end }}


