pr: none
trigger: none

pool:
  vmImage: 'ubuntu-latest'

parameters:
  - name: env
    displayName: Environment to Run Test
    type: string
    values:
      - dev
      - sit

stages:
  - stage: run
    displayName: "${{ parameters.env }} - Run"
    pool: $(deploy-pool-${{ parameters.k8sEnv }})
    jobs:
      - job: 
        displayName: "python_env (${{ parameters.env }})"
        steps:
          - script: |
              sudo apt-get install git
            displayName: 'Install GIT'

          - checkout: self
            clean: true
            persistCredentials: true