UPDATE configuration_keys SET config_value='true', config_description='Job enabled (true/false)' WHERE config_category='GLOBAL' AND config_key='scheduler.jobName_mod3CancelV2.enabled';
UPDATE configuration_keys SET config_value='Description', config_description='psp send payment' WHERE config_category='GLOBAL' AND config_key='scheduler.jobName_pspSendPayment.jobDescription';
UPDATE configuration_keys SET config_value='0;0;0;0;0;0;1;0', config_description='codifica csv tipo versamento JIF' WHERE config_category='FATTURAZIONI' AND config_key='tipoVersamento.JIF';
UPDATE configuration_keys SET config_value='Tabella aggregato versamenti', config_description=NULL WHERE config_category='info-quadr' AND config_key='commissioneCaricoPsp.pdf.aggregato.header';
UPDATE configuration_keys SET config_value='TIMEOUT_C', config_description='timeout' WHERE config_category='GLOBAL' AND config_key='timeout.paaAttivaRPT.pull';
UPDATE configuration_keys SET config_value='01386030488', config_description='Indicare qui idDominio della PA MdG sulle cui RPT si deve applicare la trasformazione. Eventuali identificativi devono essere separati dal carattere "," (virgola)' WHERE config_category='rpt-invia' AND config_key='patch.ministeroDiGiustizia.idDominio';
UPDATE configuration_keys SET config_value='IT', config_description='nazioneAttestante' WHERE config_category='GLOBAL' AND config_key='istitutoAttestante.nazioneAttestante';
UPDATE configuration_keys SET config_value='0;0;0;0;1;0;0;0', config_description='codifica csv tipo versamento CP' WHERE config_category='FATTURAZIONI' AND config_key='tipoVersamento.CP';
UPDATE configuration_keys SET config_value='0 0 0/1 ? * * *', config_description='Cron expression (Es.[*/10 * * ? * *] will fire every ten seconds)' WHERE config_category='GLOBAL' AND config_key='scheduler.jobName_rtPullRecoveryPush.cronExpression';
UPDATE configuration_keys SET config_value='TIMEOUT_B', config_description='Tipo timeout' WHERE config_category='GLOBAL' AND config_key='timeout.pspInviaCarrelloRPTCarte';
UPDATE configuration_keys SET config_value='true', config_description=NULL WHERE config_category='info-wisp' AND config_key='chiediListaPSP.outputJsonValid';
UPDATE configuration_keys SET config_value='true', config_description=NULL WHERE config_category='GLOBAL' AND config_key='mybank.params.passaggioCodiceMyBank';
UPDATE configuration_keys SET config_value='TIMEOUT_C', config_description='Tipo timeout' WHERE config_category='GLOBAL' AND config_key='timeout.pspInviaAckRT';
UPDATE configuration_keys SET config_value='00187', config_description='capAttestante' WHERE config_category='GLOBAL' AND config_key='istitutoAttestante.capAttestante';
UPDATE configuration_keys SET config_value='true', config_description='Job enabled (true/false)' WHERE config_category='GLOBAL' AND config_key='scheduler.jobName_mod3UpdateNotifiedPositionPayment.enabled';
UPDATE configuration_keys SET config_value='true', config_description=NULL WHERE config_category='info-quadr' AND config_key='commissioneCaricoPa.invio.mail';
UPDATE configuration_keys SET config_value='2', config_description='cache validity days outcome ok' WHERE config_category='GLOBAL' AND config_key='idempotency.outcome.ok.duration.days';
UPDATE configuration_keys SET config_value='false', config_description='Suspend all jobs for release' WHERE config_category='GLOBAL' AND config_key='scheduler.suspendAllJobs';
UPDATE configuration_keys SET config_value='0 0 * ? * * *', config_description='Cron expression (Es.[*/10 * * ? * *] will fire every ten seconds)' WHERE config_category='GLOBAL' AND config_key='scheduler.jobName_pspRetryNotificheCancellazioneRpt.cronExpression';
UPDATE configuration_keys SET config_value='n.a.', config_description=NULL WHERE config_category='info-quadr' AND config_key='commissioneCaricoPa.pdf.aggregato.footer';
UPDATE configuration_keys SET config_value='1', config_description='parkedList pollerMinutesToBack' WHERE config_category='GLOBAL' AND config_key='parkedList_pollerMinutesToBack';
UPDATE configuration_keys SET config_value='3', config_description='numero massimo di tentativi per NodoChiediAvanzamento da PM' WHERE config_category='GLOBAL' AND config_key='maxChiediAvanzamento';
UPDATE configuration_keys SET config_value='n.a.', config_description=NULL WHERE config_category='info-quadr' AND config_key='commissioneCaricoPsp.pdf.dettaglio.footer';
UPDATE configuration_keys SET config_value='https://api.dev.platform.pagopa.it/wfesp/api/v1/redirect', config_description='Redirect wfesp' WHERE config_category='GLOBAL' AND config_key='uri.wfesp';
UPDATE configuration_keys SET config_value='0;0;1;0;0;0;0;0', config_description='codifica csv tipo versamento AD' WHERE config_category='FATTURAZIONI' AND config_key='tipoVersamento.AD';
UPDATE configuration_keys SET config_value='0/30 * * ? * * *', config_description='Cron expression (Es.[*/10 * * ? * *] will fire every ten seconds)' WHERE config_category='GLOBAL' AND config_key='scheduler.jobName_pspChiediAvanzamentoRpt.cronExpression';
UPDATE configuration_keys SET config_value='AGID_01', config_description='id PSP AGID' WHERE config_category='GLOBAL' AND config_key='idPspAGID';
UPDATE configuration_keys SET config_value='PagoPA S.p.A.', config_description='denominazioneAttestante' WHERE config_category='GLOBAL' AND config_key='istitutoAttestante.denominazioneAttestante';
UPDATE configuration_keys SET config_value='2021-01-01', config_description='Job enabled (true/false)' WHERE config_category='GLOBAL' AND config_key='GLOBAL-mod3_inizio';
UPDATE configuration_keys SET config_value='pate_', config_description='cartella file rendicontazioni' WHERE config_category='GLOBAL' AND config_key='ftp.env.path';
UPDATE configuration_keys SET config_value='n.a.', config_description=NULL WHERE config_category='info-quadr' AND config_key='commissioneCaricoPa.pdf.dettaglio.footer';
UPDATE configuration_keys SET config_value='1', config_description='Minuti precedenti per cercare una retry sendPaymentResult' WHERE config_category='GLOBAL' AND config_key='scheduler.sendPaymentResultPollerMinutesBack';
UPDATE configuration_keys SET config_value='TIMEOUT_A', config_description='Tipo timeout' WHERE config_category='GLOBAL' AND config_key='timeout.paaChiediNumeroAvviso';
UPDATE configuration_keys SET config_value='Description', config_description='generazione ricevute in formato receipt' WHERE config_category='GLOBAL' AND config_key='scheduler.jobName_mod3GenerateReceipt.jobDescription';
UPDATE configuration_keys SET config_value='2', config_description='pa Send Rt max retry' WHERE config_category='GLOBAL' AND config_key='scheduler.paSendRtMaxRetry';
UPDATE configuration_keys SET config_value='5', config_description='Numero massimo di elementi nel Carrello' WHERE config_category='rpt-invia' AND config_key='inviaCarrelloRpt.maxNumRptInCart';
UPDATE configuration_keys SET config_value='true', config_description='Job enabled (true/false)' WHERE config_category='GLOBAL' AND config_key='scheduler.jobName_generaRendicontazioneBollo.enabled';
UPDATE configuration_keys SET config_value='true', config_description='Job enabled (true/false)' WHERE config_category='GLOBAL' AND config_key='scheduler.jobName_paRetryPaInviaRtNegative.enabled';
UPDATE configuration_keys SET config_value='http://url.fittizio', config_description='urlFittizioRedirectEC' WHERE config_category='GLOBAL' AND config_key='urlFittizioRedirectEC';
UPDATE configuration_keys SET config_value='0 0/2 * ? * * *', config_description='Cron expression (Es.[*/10 * * ? * *] will fire every ten seconds)' WHERE config_category='GLOBAL' AND config_key='scheduler.jobName_annullamentoRptMaiRichiesteDaPm.cronExpression';
UPDATE configuration_keys SET config_value='TassaAutomobilistica_1_0_0.xsd', config_description='-' WHERE config_category='rpt-modello4' AND config_key='xsdRiferimentoBolloAuto';
UPDATE configuration_keys SET config_value='0/30 * * ? * * *', config_description='Cron expression (Es.[*/10 * * ? * *] will fire every ten seconds)' WHERE config_category='GLOBAL' AND config_key='scheduler.jobName_pspChiediListaAndChiediRt.cronExpression';
UPDATE configuration_keys SET config_value='TIMEOUT_A', config_description='Tipo timeout' WHERE config_category='GLOBAL' AND config_key='timeout.paaVerificaRPT';
UPDATE configuration_keys SET config_value='10.10.39.132', config_description=NULL WHERE config_category='info-quadr' AND config_key='smtp.host';
UPDATE configuration_keys SET config_value='TIMEOUT_A', config_description='Tipo timeout' WHERE config_category='GLOBAL' AND config_key='timeout.paDemandPaymentNotice';
UPDATE configuration_keys SET config_value='true', config_description='Job enabled (true/false) - sitOrd per quelle in P_WAITING' WHERE config_category='GLOBAL' AND config_key='scheduler.jobName_situazioneOrdine.enabled';
UPDATE configuration_keys SET config_value='97735020584_03', config_description='identificativo canale Cittadinanza Digitale' WHERE config_category='GLOBAL' AND config_key='idCanaleCD';
UPDATE configuration_keys SET config_value='true', config_description='paInviaRtRecovery enabled' WHERE config_category='GLOBAL' AND config_key='scheduler.jobName_paInviaRtRecovery.enabled';
UPDATE configuration_keys SET config_value='Report commissioniCaricoPsp', config_description=NULL WHERE config_category='info-quadr' AND config_key='commissioneCaricoPsp.template.subject.mail';
UPDATE configuration_keys SET config_value='SIA', config_description=NULL WHERE config_category='rendicontazioni' AND config_key='bollo.codiceIdentificativo.1';
UPDATE configuration_keys SET config_value='2', config_description='cache validity days outcome ko' WHERE config_category='GLOBAL' AND config_key='idempotency.outcome.ko.duration.days';
UPDATE configuration_keys SET config_value='true', config_description='-' WHERE config_category='rpt-info' AND config_key='chiediInfoPagamento.outputJsonValid';
UPDATE configuration_keys SET config_value='TIMEOUT_A', config_description='timeout' WHERE config_category='GLOBAL' AND config_key='timeout.pspNotifyPayment';
UPDATE configuration_keys SET config_value='Milano', config_description='Dati dell''intermediario della trasmissione/ Comune domicilio fiscale' WHERE config_category='rendicontazioni' AND config_key='bollo.intermediario.comuneDomicilioFiscale';
UPDATE configuration_keys SET config_value='10', config_description='totale minuti per cui una richiesta non è mai stata processata da WISP2' WHERE config_category='GLOBAL' AND config_key='scheduler.annullamentoRptMaiRichiesteDaPmPollerMinutesToBack';
UPDATE configuration_keys SET config_value='15376371009', config_description='idPspMod3New' WHERE config_category='GLOBAL' AND config_key='idPspMod3New';
UPDATE configuration_keys SET config_value='Description', config_description='invio receipt verso Stazioni PA' WHERE config_category='GLOBAL' AND config_key='scheduler.jobName_paSendRt.jobDescription';
UPDATE configuration_keys SET config_value='Description', config_description='Description' WHERE config_category='GLOBAL' AND config_key='scheduler.jobName_pspRetryAckNegative.jobDescription';
UPDATE configuration_keys SET config_value='Description', config_description='cancellazione position payment con token scaduti modello 3' WHERE config_category='GLOBAL' AND config_key='scheduler.jobName_mod3Cancel.jobDescription';
UPDATE configuration_keys SET config_value='', config_description='tipi versamento non accettati per closePaymentV2 per pagamenti IO/Checkout' WHERE config_category='GLOBAL' AND config_key='closePaymentV2DenyListTipoVersamento';
UPDATE configuration_keys SET config_value='0;0;0;0;0;0;0;1', config_description='codifica csv tipo versamento MYBK' WHERE config_category='FATTURAZIONI' AND config_key='tipoVersamento.MYBK';
UPDATE configuration_keys SET config_value='Piazza Colonna', config_description='indirizzoAttestante' WHERE config_category='GLOBAL' AND config_key='istitutoAttestante.indirizzoAttestante';
UPDATE configuration_keys SET config_value='true', config_description='Job enabled (true/false)' WHERE config_category='GLOBAL' AND config_key='scheduler.jobName_mod3Riconciliazione.enabled';
UPDATE configuration_keys SET config_value='370', config_description='civicoAttestante' WHERE config_category='GLOBAL' AND config_key='istitutoAttestante.civicoAttestante';
UPDATE configuration_keys SET config_value='TBD', config_description='id PSP Checkout' WHERE config_category='GLOBAL' AND config_key='idPspCheckout';
UPDATE configuration_keys SET config_value='TIMEOUT_B', config_description='Tipo timeout' WHERE config_category='GLOBAL' AND config_key='timeout.pspInviaRPT';
UPDATE configuration_keys SET config_value='Tabella aggregato versamenti', config_description=NULL WHERE config_category='info-quadr' AND config_key='commissioneCaricoPa.pdf.aggregato.header';
UPDATE configuration_keys SET config_value='true', config_description='use idempotency' WHERE config_category='GLOBAL' AND config_key='useIdempotency';
UPDATE configuration_keys SET config_value='true', config_description=NULL WHERE config_category='rpt-invia' AND config_key='mybank.params.passaggioCodiceMyBank';
UPDATE configuration_keys SET config_value='ABC', config_description='id PSP LisPay,divisi da virgola' WHERE config_category='info-wisp' AND config_key='chiediListaPSP.listaPspLisPay';
UPDATE configuration_keys SET config_value='Nessun dato disponibile per il mese di riferimento', config_description=NULL WHERE config_category='info-quadr' AND config_key='commissioneCaricoPa.noData.message';
UPDATE configuration_keys SET config_value='Description', config_description='Riconciliazione rpt' WHERE config_category='GLOBAL' AND config_key='scheduler.jobName_mod3Riconciliazione.jobDescription';
UPDATE configuration_keys SET config_value='00493410583', config_description='identificativo Automobile Club Italia' WHERE config_category='rpt-modello4' AND config_key='aciId';
UPDATE configuration_keys SET config_value='true', config_description='Job enabled (true/false)' WHERE config_category='GLOBAL' AND config_key='scheduler.jobName_pspChiediAvanzamentoRpt.enabled';
UPDATE configuration_keys SET config_value='true', config_description='Job enabled (true/false)' WHERE config_category='GLOBAL' AND config_key='scheduler.jobName_mod3CancelV1.enabled';
UPDATE configuration_keys SET config_value='1', config_description='validitÃ  verifica bollettino' WHERE config_category='GLOBAL' AND config_key='verificabollettino.validity.minutes';
UPDATE configuration_keys SET config_value='true', config_description='jobName_idempotencyCacheClean enabled/disabled' WHERE config_category='GLOBAL' AND config_key='scheduler.jobName_idempotencyCacheClean.enabled';
UPDATE configuration_keys SET config_value='Description', config_description='Description' WHERE config_category='GLOBAL' AND config_key='scheduler.jobName_pspChiediAvanzamentoRpt.jobDescription';
UPDATE configuration_keys SET config_value='Tassa automobilistica', config_description='-' WHERE config_category='rpt-modello4' AND config_key='descrizioneServizioBolloAuto';
UPDATE configuration_keys SET config_value='Description', config_description='Riconciliazione rpt' WHERE config_category='GLOBAL' AND config_key='scheduler.jobName_mod3RiconciliazioneRt.jobDescription';
UPDATE configuration_keys SET config_value='wpl04', config_description='identificativo plugin MyBank' WHERE config_category='GLOBAL' AND config_key='idPlugin.mybank';
UPDATE configuration_keys SET config_value='07601', config_description='Check iban poste match' WHERE config_category='info-wisp' AND config_key='chiediListaPSP.ibanPosteMatch';
UPDATE configuration_keys SET config_value='2', config_description=NULL WHERE config_category='GLOBAL' AND config_key='inviaCarrelloRpt.maxNumRptInCartMultibeneficiario';
UPDATE configuration_keys SET config_value='97735020584_02', config_description='identificativo canale AGID' WHERE config_category='GLOBAL' AND config_key='idCanaleAGID';
UPDATE configuration_keys SET config_value='3600000', config_description=' default millisecondi validità token IO' WHERE config_category='GLOBAL' AND config_key='default_durata_token_IO';
UPDATE configuration_keys SET config_value='0;1;0;0;0;0;0;0', config_description='codifica csv tipo versamento BP' WHERE config_category='FATTURAZIONI' AND config_key='tipoVersamento.BP';
UPDATE configuration_keys SET config_value='0/30 * * ? * * *', config_description='Cron expression (Es.[*/10 * * ? * *] will fire every ten seconds)' WHERE config_category='GLOBAL' AND config_key='scheduler.jobName_paInviaRt.cronExpression';
UPDATE configuration_keys SET config_value='G', config_description='CtIdentificativoUnivoco.tipoIdentificativoUnivoco' WHERE config_category='GLOBAL' AND config_key='istitutoAttestante.identificativoUnivocoAttestante.tipoIdentificativoUnivoco';
UPDATE configuration_keys SET config_value='1', config_description='cancel IO Payment Minutes To Back' WHERE config_category='GLOBAL' AND config_key='scheduler.cancelIOPaymentActorMinutesToBack';
UPDATE configuration_keys SET config_value='0;0;0;0;0;1;0;0', config_description='codifica csv tipo versamento PO' WHERE config_category='FATTURAZIONI' AND config_key='tipoVersamento.PO';
UPDATE configuration_keys SET config_value='true', config_description='Validazione XSD output Bundle' WHERE config_category='GLOBAL' AND config_key='validate_output';
UPDATE configuration_keys SET config_value='Description', config_description='Description' WHERE config_category='GLOBAL' AND config_key='scheduler.jobName_ftpUpload.jobDescription';
UPDATE configuration_keys SET config_value='TIMEOUT_A', config_description='timeout' WHERE config_category='GLOBAL' AND config_key='timeout.paGetPayment';
UPDATE configuration_keys SET config_value='Description', config_description='Description' WHERE config_category='GLOBAL' AND config_key='scheduler.jobName_annullamentoRptMaiRichiesteDaPm.jobDescription';
UPDATE configuration_keys SET config_value='POSTE1', config_description=NULL WHERE config_category='info-wisp' AND config_key='chiediListaPSP.listaIdPoste';
UPDATE configuration_keys SET config_value='true', config_description='Job enabled (true/false)' WHERE config_category='GLOBAL' AND config_key='scheduler.jobName_mod3GenerateReceipt.enabled';
UPDATE configuration_keys SET config_value='true', config_description='Job enabled (true/false)' WHERE config_category='GLOBAL' AND config_key='scheduler.jobName_mod3RiconciliazioneRt.enabled';
UPDATE configuration_keys SET config_value='false', config_description='restituisce come risposta alla nodoChiediInformativaPSP un SYSTEM_ERROR' WHERE config_category='info-pa-psp' AND config_key='disableNodoChiediInformativaPSP';
UPDATE configuration_keys SET config_value='0;0;0;0;1;0;0;0', config_description='codifica csv tipo versamento TPAY' WHERE config_category='FATTURAZIONI' AND config_key='tipoVersamento.TPAY';
UPDATE configuration_keys SET config_value='TIMEOUT_B', config_description='Tipo timeout' WHERE config_category='GLOBAL' AND config_key='timeout.pspInviaCarrelloRPT';
UPDATE configuration_keys SET config_value='Nessun dato disponibile per il mese di riferimento', config_description=NULL WHERE config_category='info-quadr' AND config_key='commissioneCaricoPsp.noData.message';
UPDATE configuration_keys SET config_value='10', config_description='maxOccurences to GEC service fees' WHERE config_category='GLOBAL' AND config_key='gec.fees.maxOccurences';
UPDATE configuration_keys SET config_value='TIMEOUT_C', config_description='Tipo timeout' WHERE config_category='GLOBAL' AND config_key='timeout.pspChiediListaRT';
UPDATE configuration_keys SET config_value='prova@prova.com', config_description=NULL WHERE config_category='info-quadr' AND config_key='commissioneCaricoPsp.template.sender.address.mail';
UPDATE configuration_keys SET config_value='Tabella dettaglio versamenti', config_description=NULL WHERE config_category='info-quadr' AND config_key='commissioneCaricoPsp.pdf.dettaglio.header';
UPDATE configuration_keys SET config_value='get', config_description=NULL WHERE config_category='GLOBAL' AND config_key='httpmethod.wfesp.pa2wfesp';
UPDATE configuration_keys SET config_value='Tabella dettaglio versamenti', config_description=NULL WHERE config_category='info-quadr' AND config_key='commissioneCaricoPa.pdf.dettaglio.header';
UPDATE configuration_keys SET config_value='Description', config_description='Riconciliazione rpt' WHERE config_category='GLOBAL' AND config_key='scheduler.jobName_mod3RiconciliazioneRpt.jobDescription';
UPDATE configuration_keys SET config_value='Description', config_description='Description' WHERE config_category='GLOBAL' AND config_key='scheduler.jobName_paRetryPaInviaRtNegative.jobDescription';
UPDATE configuration_keys SET config_value='3', config_description='maxRetry to GEC service fees' WHERE config_category='GLOBAL' AND config_key='gec.fees.maxRetry';
UPDATE configuration_keys SET config_value='true', config_description='Job enabled (true/false)' WHERE config_category='GLOBAL' AND config_key='scheduler.jobName_pspNotificaCancellazione.enabled';
UPDATE configuration_keys SET config_value='n.a.', config_description=NULL WHERE config_category='info-quadr' AND config_key='commissioneCaricoPsp.pdf.aggregato.footer';
UPDATE configuration_keys SET config_value='pda@dev.test', config_description=NULL WHERE config_category='info-quadr' AND config_key='smtp.username';
UPDATE configuration_keys SET config_value='1026', config_description=NULL WHERE config_category='info-quadr' AND config_key='smtp.port';
UPDATE configuration_keys SET config_value='97735020584', config_description='identificativo intermediario PSP Cittadinanza Digitale' WHERE config_category='GLOBAL' AND config_key='intPspCD';
UPDATE configuration_keys SET config_value='*/2 * * * *', config_description='Cron expression (Es.[*/10 * * ? * *] will fire every ten seconds)' WHERE config_category='GLOBAL' AND config_key='scheduler.jobName_situazioneOrdine.cronExpression';
UPDATE configuration_keys SET config_value='true', config_description='Job enabled (true/false)' WHERE config_category='GLOBAL' AND config_key='scheduler.jobName_ftpUpload.enabled';
UPDATE configuration_keys SET config_value='SIA S.p.A.', config_description='Dati dell''intermediario della trasmissione/ Denominazione' WHERE config_category='rendicontazioni' AND config_key='bollo.intermediario.denominazione';
UPDATE configuration_keys SET config_value='test value', config_description='this is a test' WHERE config_category='Z7HuDfyuFpvmg6KBF3i6FQ17SA6W0FiiC2F' AND config_key='conf-key';
UPDATE configuration_keys SET config_value='5', config_description='numero massimo di tentativi di re-invio delle RT alla PA' WHERE config_category='GLOBAL' AND config_key='scheduler.paRetryPaInviaRtNegativePollerMaxRetry';
UPDATE configuration_keys SET config_value='60', config_description='Description' WHERE config_category='GLOBAL' AND config_key='scheduler.jobName_refreshConfiguration.jobDescription';
UPDATE configuration_keys SET config_value='n/a', config_description='denomUnitOperAttestante' WHERE config_category='GLOBAL' AND config_key='istitutoAttestante.denomUnitOperAttestante';
UPDATE configuration_keys SET config_value='0;0;0;0;0;0;0;0', config_description='codifica csv tipo versamento POS' WHERE config_category='FATTURAZIONI' AND config_key='tipoVersamento.POS';
UPDATE configuration_keys SET config_value='Description', config_description='Description' WHERE config_category='GLOBAL' AND config_key='scheduler.jobName_generaRendicontazioneBollo.jobDescription';
UPDATE configuration_keys SET config_value='true', config_description='Job enabled (true/false)' WHERE config_category='GLOBAL' AND config_key='scheduler.jobName_pspChiediListaAndChiediRt.enabled';
UPDATE configuration_keys SET config_value='5', config_description='Retry psp sent payment max retries' WHERE config_category='GLOBAL' AND config_key='scheduler.retryPspSendPayment';
UPDATE configuration_keys SET config_value='30', config_description=' indica i minuti che devono passare per un ordine prima di eseguire la Situazione Ordine - job "check"' WHERE config_category='GLOBAL' AND config_key='scheduler.situazioneOrdineCheckMinutesToFilter';
UPDATE configuration_keys SET config_value='TIMEOUT_B', config_description='timeout' WHERE config_category='GLOBAL' AND config_key='timeout.paSendRT';
UPDATE configuration_keys SET config_value='36892710904_02', config_description='id Canale eCommerce' WHERE config_category='GLOBAL' AND config_key='idCanaleECommerce';
UPDATE configuration_keys SET config_value='true', config_description='popolare il CCP nella paaVerificaRPT generata dal traduttore con NMP_[random 10 numeri]' WHERE config_category='GLOBAL' AND config_key='ccpRandomTraduttore';
UPDATE configuration_keys SET config_value='true', config_description='set true or false se si usa smtp server test' WHERE config_category='info-quadr' AND config_key='smtp.test.sia';
UPDATE configuration_keys SET config_value='TIMEOUT_A', config_description='Tipo timeout' WHERE config_category='GLOBAL' AND config_key='timeout.paVerifyPaymentNotice';
UPDATE configuration_keys SET config_value='false', config_description=' flag di ON/OFF se usare primitiva pspNotifyPayment per PayPal' WHERE config_category='GLOBAL' AND config_key='usePspNotifyPayment';
UPDATE configuration_keys SET config_value='true', config_description='Job enabled (true/false)' WHERE config_category='GLOBAL' AND config_key='scheduler.jobName_paSendRt.enabled';
UPDATE configuration_keys SET config_value='NodoDeiPagamentiSPC', config_description='identificativo del nodo per valorizzazione dell''elemento id nel Fault Bean, in caso di errore generato dal FESP' WHERE config_category='rt-invia' AND config_key='idFaultBean.nodo';
UPDATE configuration_keys SET config_value='TBD', config_description='id Canale Checkout' WHERE config_category='GLOBAL' AND config_key='idCanaleCheckout';
UPDATE configuration_keys SET config_value='1', config_description='cache validity days activate ko' WHERE config_category='GLOBAL' AND config_key='idempotency.activate.ko.duration.days';
UPDATE configuration_keys SET config_value='true', config_description='check mod3 descoping' WHERE config_category='GLOBAL' AND config_key='mod3_descoping';
UPDATE configuration_keys SET config_value='true', config_description='Job enabled (true/false) - da P_READY a P_WAITING' WHERE config_category='GLOBAL' AND config_key='scheduler.jobName_situazioneOrdineCheck.enabled';
UPDATE configuration_keys SET config_value='Description', config_description='Description' WHERE config_category='GLOBAL' AND config_key='scheduler.jobName_pspRetryNotificheCancellazioneRpt.jobDescription';
UPDATE configuration_keys SET config_value='TIMEOUT_A', config_description='Tipo timeout' WHERE config_category='GLOBAL' AND config_key='timeout.paaAttivaRPT';
UPDATE configuration_keys SET config_value='true', config_description='sendBizEventsToEventHub' WHERE config_category='GLOBAL' AND config_key='sendBizEventsToEventHub';
UPDATE configuration_keys SET config_value='true', config_description=NULL WHERE config_category='info-quadr' AND config_key='commissioneCaricoPsp.invio.mail';
UPDATE configuration_keys SET config_value='10', config_description='timeout' WHERE config_category='GLOBAL' AND config_key='default_idempotency_key_validity_minutes';
UPDATE configuration_keys SET config_value='1', config_description=NULL WHERE config_category='GLOBAL' AND config_key='inviaCarrelloRpt.maxVersamentiInSecondRptMultibeneficiario';
UPDATE configuration_keys SET config_value='true', config_description='Job enabled (true/false)' WHERE config_category='GLOBAL' AND config_key='scheduler.jobName_pspRetryNotificheCancellazioneRpt.enabled';
UPDATE configuration_keys SET config_value='esitoMS', config_description=NULL WHERE config_category='GLOBAL' AND config_key='httpmethod.wfesp.psp2wfespMS';
UPDATE configuration_keys SET config_value='0.0.0.0', config_description=NULL WHERE config_category='rendicontazioni' AND config_key='ftp.internalFTPComponentEndpointHost';
UPDATE configuration_keys SET config_value='Description', config_description='processo di recovery che parte dal WFESP' WHERE config_category='GLOBAL' AND config_key='scheduler.jobName_situazioneOrdine.jobDescription';
UPDATE configuration_keys SET config_value='0/30 * * ? * * *', config_description='Cron expression (Es.[*/10 * * ? * *] will fire every ten seconds)' WHERE config_category='GLOBAL' AND config_key='scheduler.jobName_pspRetryAckNegative.cronExpression';
UPDATE configuration_keys SET config_value='true', config_description='Job enabled (true/false)' WHERE config_category='GLOBAL' AND config_key='scheduler.jobName_pspSendPayment.enabled';
UPDATE configuration_keys SET config_value='TIMEOUT_B', config_description='Tipo timeout' WHERE config_category='GLOBAL' AND config_key='timeout.paaInviaRT.push';
UPDATE configuration_keys SET config_value='TIMEOUT_A', config_description='Tipo timeout' WHERE config_category='GLOBAL' AND config_key='timeout.cdInfoWisp';
UPDATE configuration_keys SET config_value='1800000', config_description=' default millisecondi validità token' WHERE config_category='GLOBAL' AND config_key='default_token_duration_validity_millis';
UPDATE configuration_keys SET config_value='PPT', config_description=NULL WHERE config_category='info-quadr' AND config_key='commissioneCaricoPa.template.sender.name.mail';
UPDATE configuration_keys SET config_value='TIMEOUT_C', config_description='Tipo timeout' WHERE config_category='GLOBAL' AND config_key='timeout.pspChiediRT';
UPDATE configuration_keys SET config_value='TIMEOUT_B', config_description='Tipo timeout' WHERE config_category='GLOBAL' AND config_key='timeout.pspChiediAvanzamentoRPT';
UPDATE configuration_keys SET config_value='true', config_description='toggle per abilitare o disabilitare contatori NodoChiediAvanzamento' WHERE config_category='GLOBAL' AND config_key='useCountChiediAvanzamento';
UPDATE configuration_keys SET config_value='http://localhost:8080', config_description='Validazione XSD input Bundle' WHERE config_category='GLOBAL' AND config_key='paymentmanager.baseurl';
UPDATE configuration_keys SET config_value='true', config_description='Flag di attivazione della patch' WHERE config_category='rpt-invia' AND config_key='patch.ministeroDiGiustizia.active';
UPDATE configuration_keys SET config_value='0 0 0 ? * * *', config_description='Cron expression (Es.[*/10 * * ? * *] will fire every ten seconds)' WHERE config_category='GLOBAL' AND config_key='scheduler.jobName_generaRendicontazioneBollo.cronExpression';
UPDATE configuration_keys SET config_value='0/30 * * ? * * *', config_description='Cron expression (Es.[*/10 * * ? * *] will fire every ten seconds)' WHERE config_category='GLOBAL' AND config_key='scheduler.jobName_paRetryPaInviaRtNegative.cronExpression';
UPDATE configuration_keys SET config_value='0;0;0;0;1;0;0;0', config_description='codifica csv tipo versamento PPAL' WHERE config_category='FATTURAZIONI' AND config_key='tipoVersamento.PPAL';
UPDATE configuration_keys SET config_value='2021-01-01', config_description='Job enabled (true/false)' WHERE config_category='GLOBAL' AND config_key='mod3_inizio';
UPDATE configuration_keys SET config_value='Roma', config_description='localitaAttestante' WHERE config_category='GLOBAL' AND config_key='istitutoAttestante.localitaAttestante';
UPDATE configuration_keys SET config_value='6.1', config_description='Versione Quadrature' WHERE config_category='info-quadr' AND config_key='versioneQuadrature';
UPDATE configuration_keys SET config_value='AGID_01', config_description='id PSP Cittadinanza Digitale' WHERE config_category='GLOBAL' AND config_key='idPspCD';
UPDATE configuration_keys SET config_value='*/1 * * * *', config_description='Cron expression (Es.[*/10 * * ? * *] will fire every ten seconds)' WHERE config_category='GLOBAL' AND config_key='scheduler.jobName_situazioneOrdineCheck.cronExpression';
UPDATE configuration_keys SET config_value='0', config_description='timeout' WHERE config_category='GLOBAL' AND config_key='scheduler.mod3Cancel.minutesWaitPaOld';
UPDATE configuration_keys SET config_value='10', config_description='Minuti di validita chiave idempotenza' WHERE config_category='GLOBAL' AND config_key='payment_activation_validity_minutes';
UPDATE configuration_keys SET config_value='TIMEOUT_C', config_description='Tipo timeout' WHERE config_category='GLOBAL' AND config_key='timeout.paSendRT.pull';
UPDATE configuration_keys SET config_value='9610', config_description=NULL WHERE config_category='rendicontazioni' AND config_key='ftp.internalFTPComponentEndpointPort';
UPDATE configuration_keys SET config_value='true', config_description='Flag che indica se il PM dovrà ricevere i nuovi campi di infoPagamento' WHERE config_category='GLOBAL' AND config_key='flag.chiediInfoPagamento.useNewField';
UPDATE configuration_keys SET config_value='100', config_description='parkedList maxOccur' WHERE config_category='GLOBAL' AND config_key='parkedList_maxOccur';
UPDATE configuration_keys SET config_value='Description', config_description='retry attiva rpt ' WHERE config_category='GLOBAL' AND config_key='scheduler.jobName_paRetryAttivaRpt.jobDescription';
UPDATE configuration_keys SET config_value='true', config_description='Job enabled (true/false)' WHERE config_category='GLOBAL' AND config_key='scheduler.jobName_paRetryAttivaRpt.enabled';
UPDATE configuration_keys SET config_value='15376371009_01', config_description='idCanaleMod3New' WHERE config_category='GLOBAL' AND config_key='idCanaleMod3New';
UPDATE configuration_keys SET config_value='Automobile Club d''Italia', config_description='descrizione Automobile Club Italia' WHERE config_category='rpt-modello4' AND config_key='aciDescrizione';
UPDATE configuration_keys SET config_value='Description', config_description='Mod3 update notified Position Payment' WHERE config_category='GLOBAL' AND config_key='scheduler.jobName_mod3UpdateNotifiedPositionPayment.jobDescription';
UPDATE configuration_keys SET config_value='8', config_description='giorni per cui non si sono completate RPT' WHERE config_category='GLOBAL' AND config_key='scheduler.rptExpiringDays';
UPDATE configuration_keys SET config_value='n/a', config_description='codiceUnitOperAttestante' WHERE config_category='GLOBAL' AND config_key='istitutoAttestante.codiceUnitOperAttestante';
UPDATE configuration_keys SET config_value='Description', config_description='Description' WHERE config_category='GLOBAL' AND config_key='scheduler.jobName_paInviaRt.jobDescription';
UPDATE configuration_keys SET config_value='0 0 1 ? * * *', config_description='Cron expression (Es.[*/10 * * ? * *] will fire every ten seconds)' WHERE config_category='GLOBAL' AND config_key='scheduler.jobName_pspNotificaCancellazione.cronExpression';
UPDATE configuration_keys SET config_value='true', config_description='Job enabled (true/false)' WHERE config_category='GLOBAL' AND config_key='scheduler.jobName_positionRetrySendPaymentResult.enabled';
UPDATE configuration_keys SET config_value='Description', config_description='processo di recovery che parte dal WFESP per tutte le redirect in stato P_READY' WHERE config_category='GLOBAL' AND config_key='scheduler.jobName_situazioneOrdineCheck.jobDescription';
UPDATE configuration_keys SET config_value='1', config_description='numero massimo di tentativi di re-invio ACK al PSP' WHERE config_category='GLOBAL' AND config_key='scheduler.pspRetryAckNegativePollerMaxRetry';
UPDATE configuration_keys SET config_value='PPT', config_description=NULL WHERE config_category='info-quadr' AND config_key='commissioneCaricoPsp.template.sender.name.mail';
UPDATE configuration_keys SET config_value='true', config_description='Validazione XSD input Bundle' WHERE config_category='GLOBAL' AND config_key='validate_input';
UPDATE configuration_keys SET config_value='true', config_description='Job enabled (true/false)' WHERE config_category='GLOBAL' AND config_key='scheduler.jobName_mod3RiconciliazioneRpt.enabled';
UPDATE configuration_keys SET config_value='true', config_description='abilitazione scrittura re su eventhub azure PagoPA' WHERE config_category='GLOBAL' AND config_key='azureSdkClientReEventEnabled';
UPDATE configuration_keys SET config_value='3600000', config_description=' default millisecondi validità token IO estesa' WHERE config_category='GLOBAL' AND config_key='default_durata_estensione_token_IO';
UPDATE configuration_keys SET config_value='RM', config_description='provinciaAttestante' WHERE config_category='GLOBAL' AND config_key='istitutoAttestante.provinciaAttestante';
UPDATE configuration_keys SET config_value='true', config_description='Job enabled (true/false)' WHERE config_category='GLOBAL' AND config_key='scheduler.jobName_pspRetryAckNegative.enabled';
UPDATE configuration_keys SET config_value='MI', config_description='Dati dell''intermediario della trasmissione/ Sigle della provincia del domicilio fiscale' WHERE config_category='rendicontazioni' AND config_key='bollo.intermediario.siglaDellaProvinciaDelDomicilioFiscale';
UPDATE configuration_keys SET config_value='5', config_description='Numero massimo di tentativi di re-invio sendPaymentResult al PM' WHERE config_category='GLOBAL' AND config_key='scheduler.sendPaymentResultPollerMaxRetry';
UPDATE configuration_keys SET config_value='0;0;0;1;0;0;0;0', config_description='codifica csv tipo versamento OBEP' WHERE config_category='FATTURAZIONI' AND config_key='tipoVersamento.OBEP';
UPDATE configuration_keys SET config_value='true', config_description='Job enabled (true/false)' WHERE config_category='GLOBAL' AND config_key='scheduler.jobName_rtPullRecoveryPush.enabled';
UPDATE configuration_keys SET config_value='15376371009', config_description=NULL WHERE config_category='rendicontazioni' AND config_key='bollo.mittente.codiceFiscale';
UPDATE configuration_keys SET config_value='Description', config_description='Description' WHERE config_category='GLOBAL' AND config_key='scheduler.jobName_rtPullRecoveryPush.jobDescription';
UPDATE configuration_keys SET config_value='true', config_description='Job enabled (true/false)' WHERE config_category='GLOBAL' AND config_key='scheduler.jobName_mod3Cancel.enabled';
UPDATE configuration_keys SET config_value='TIMEOUT_C', config_description='Tipo timeout' WHERE config_category='GLOBAL' AND config_key='timeout.pspNotificaCancellazioneRPT';
UPDATE configuration_keys SET config_value='BBT', config_description='tipo versamento restituito durante la chiedi scelta Wisp' WHERE config_category='GLOBAL' AND config_key='chiediSceltaWisp.tipoVersamento';
UPDATE configuration_keys SET config_value='1;0;0;0;0;0;0;0', config_description='codifica csv tipo versamento BBT' WHERE config_category='FATTURAZIONI' AND config_key='tipoVersamento.BBT';
UPDATE configuration_keys SET config_value='0;0;0;0;1;0;0;0', config_description='codifica csv tipo versamento BPAY' WHERE config_category='FATTURAZIONI' AND config_key='tipoVersamento.BPAY';
UPDATE configuration_keys SET config_value='true', config_description='attivazione retry su outcome scaduto mod3' WHERE config_category='GLOBAL' AND config_key='outcome_retry_active';
UPDATE configuration_keys SET config_value='15376371009', config_description='CtIdentificativoUnivoco.codiceIdentificativoUnivoco' WHERE config_category='GLOBAL' AND config_key='istitutoAttestante.identificativoUnivocoAttestante.codiceIdentificativoUnivoco';
UPDATE configuration_keys SET config_value='48', config_description='parkedList pollerLimitHours' WHERE config_category='GLOBAL' AND config_key='parkedList_pollerLimitHours';
UPDATE configuration_keys SET config_value='true', config_description='Job enabled (true/false)' WHERE config_category='GLOBAL' AND config_key='scheduler.jobName_annullamentoRptMaiRichiesteDaPm.enabled';
UPDATE configuration_keys SET config_value='https://acardste.vaservices.eu:1443/wallet/welcome', config_description=NULL WHERE config_category='GLOBAL' AND config_key='uri.wallet';
UPDATE configuration_keys SET config_value='0 * 0 ? * * *', config_description='Cron expression (Es.[*/10 * * ? * *] will fire every ten seconds)' WHERE config_category='GLOBAL' AND config_key='scheduler.jobName_refreshConfiguration.cronExpression';
UPDATE configuration_keys SET config_value='POSTE3', config_description='id psp poste' WHERE config_category='GLOBAL' AND config_key='id_psp_poste';
UPDATE configuration_keys SET config_value='130', config_description='Secondi di timeout per singolo processo' WHERE config_category='GLOBAL' AND config_key='timeoutForSingleProcessSeconds';
UPDATE configuration_keys SET config_value='pda', config_description=NULL WHERE config_category='info-quadr' AND config_key='smtp.password';
UPDATE configuration_keys SET config_value='false', config_description='send receipt to pa during standin period' WHERE config_category='GLOBAL' AND config_key='invioReceiptStandin';
UPDATE configuration_keys SET config_value='36892710904', config_description='id PSP eCommerce' WHERE config_category='GLOBAL' AND config_key='idPspECommerce';
UPDATE configuration_keys SET config_value='20147', config_description='Dati dell''intermediario della trasmissione/ C.A.P. domicilio fiscale' WHERE config_category='rendicontazioni' AND config_key='bollo.intermediario.CAPDelDomicilioFiscale';
UPDATE configuration_keys SET config_value='66666666666_01', config_description='standin station' WHERE config_category='GLOBAL' AND config_key='station.stand-in';
UPDATE configuration_keys SET config_value='Description', config_description='Description' WHERE config_category='GLOBAL' AND config_key='scheduler.jobName_pspChiediListaAndChiediRt.jobDescription';
UPDATE configuration_keys SET config_value='3', config_description='numero massimo di tentativi di re-invio notifiche cancellazione al PSP' WHERE config_category='GLOBAL' AND config_key='scheduler.pspRetryNotificheCancellazioneRptPollerMaxRetry';
UPDATE configuration_keys SET config_value='Via Gonin, 36', config_description='Dati dell''intermediario della trasmissione/ Indirizzo, frazione, via e numero civico del domicilio fiscale' WHERE config_category='rendicontazioni' AND config_key='bollo.intermediario.indirizzoFrazioneViaENumeroCivicoDelDomicilioFiscale';
UPDATE configuration_keys SET config_value='false', config_description='toggle to enabled/disabled gec service' WHERE config_category='GLOBAL' AND config_key='gec.enabled';
UPDATE configuration_keys SET config_value='true', config_description='Job enabled (true/false)' WHERE config_category='GLOBAL' AND config_key='scheduler.jobName_refreshConfiguration.enabled';
UPDATE configuration_keys SET config_value='0 0/1 * ? * * *', config_description='Cron expression (Es.[*/10 * * ? * *] will fire every ten seconds)' WHERE config_category='GLOBAL' AND config_key='scheduler.jobName_ftpUpload.cronExpression';
UPDATE configuration_keys SET config_value='TIMEOUT_C', config_description='Tipo timeout' WHERE config_category='GLOBAL' AND config_key='timeout.paaInviaRT.pull';
UPDATE configuration_keys SET config_value='Description', config_description='Description' WHERE config_category='GLOBAL' AND config_key='scheduler.jobName_pspNotificaCancellazione.jobDescription';
UPDATE configuration_keys SET config_value='true', config_description='Job enabled (true/false)' WHERE config_category='GLOBAL' AND config_key='scheduler.jobName_paInviaRt.enabled';
UPDATE configuration_keys SET config_value='Description', config_description='Retry psp send payment' WHERE config_category='GLOBAL' AND config_key='scheduler.jobName_retryPspSendPayment.jobDescription';
UPDATE configuration_keys SET config_value='5', config_description='numero massimo di tentativi di re-invio file ftp' WHERE config_category='GLOBAL' AND config_key='scheduler.ftpUploadRetryPollerMaxRetry';
UPDATE configuration_keys SET config_value='5', config_description='pa attiva Rpt max retry' WHERE config_category='GLOBAL' AND config_key='scheduler.paAttivaRptMaxRetry';
UPDATE configuration_keys SET config_value='97735020584', config_description='identificativo intermediario PSP AGID' WHERE config_category='GLOBAL' AND config_key='intPspAGID';
UPDATE configuration_keys SET config_value='13212880150_07', config_description='id Canali LisPay,divisi da virgola' WHERE config_category='info-wisp' AND config_key='chiediListaPSP.listaCanaliLisPay';
UPDATE configuration_keys SET config_value='Report commissioniCaricoPa', config_description=NULL WHERE config_category='info-quadr' AND config_key='commissioneCaricoPa.template.subject.mail';
UPDATE configuration_keys SET config_value='prova@prova.com', config_description=NULL WHERE config_category='info-quadr' AND config_key='commissioneCaricoPa.template.sender.address.mail';
UPDATE configuration_keys SET config_value='00001', config_description='-' WHERE config_category='rpt-modello4' AND config_key='idServizioBolloAuto';
UPDATE configuration_keys SET config_value='1', config_description='numero massimo di tentativi di invio RPT incomplete verso il PSP' WHERE config_category='GLOBAL' AND config_key='scheduler.pspChiediAvanzamentoRptPollerMaxRetry';
UPDATE configuration_keys SET config_value='SHA256withRSA', config_description=NULL WHERE config_category='rpt-annulla' AND config_key='algoritmoFirmaRT';
UPDATE configuration_keys SET config_value='15376371009', config_description='idIntPspMod3New' WHERE config_category='GLOBAL' AND config_key='idIntPspMod3New';
UPDATE configuration_keys SET config_value='YY', config_description=NULL WHERE config_category='rendicontazioni' AND config_key='bollo.codiceIdentificativo.2';
UPDATE configuration_keys SET config_value='2017-04-30T00:00:00', config_description='-' WHERE config_category='rpt-modello4' AND config_key='dataInizioValiditaBolloAuto';
UPDATE configuration_keys SET config_value='true', config_description='Job enabled (true/false)' WHERE config_category='GLOBAL' AND config_key='scheduler.jobName_cancelIOPayment.enabled';
UPDATE configuration_keys SET config_value='esito', config_description=NULL WHERE config_category='GLOBAL' AND config_key='httpmethod.wfesp.psp2wfesp';
UPDATE configuration_keys SET config_value='yyyy-MM-dd', config_description=NULL WHERE config_category='rendicontazioni' AND config_key='bollo.dateFormat';
UPDATE configuration_keys SET config_value='3600000', config_description=' default millisecondi validità token IO' WHERE config_category='GLOBAL' AND config_key='IO_token_duration_validity_millis';
UPDATE configuration_keys SET config_value='75', config_description='wisp timeout ChiediSceltaWISP' WHERE config_category='GLOBAL' AND config_key='wisp.timeoutScelta';