apiVersion: v2
name: mock-ec-prf-chart
description: Mock EC
type: application
version: 1.2.0
appVersion: 1.2.0
dependencies:
  - name: microservice-chart
    version: 2.4.0
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
    alias: mock-ec-prf
