apiVersion: v2
name: mock-ec-prf-chart
description: Mock EC prf
type: application
version: 1.3.3
appVersion: 1.3.3
dependencies:
  - name: microservice-chart
    version: 2.4.0
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
